import{defaultInteractionSettings,type ManifestProgram,type ProblemManifest,type ProgramRole,type StoredBlob}from'@problemforge/contracts';
import{PackageError,safePath}from'./archive.ts';import{readXml,escapeXml as x,type Xml}from'./xml.ts';import{blankManifest,selectManifest,digest}from'./native.ts';import type{Exporter,ImportResult,Issue,Profile}from'./types.ts';
const languageNames:Record<string,string>={english:'en',russian:'ru',chinese:'zh-CN'};
const sourceTypes:Record<string,Profile['language']>={'cpp.g++17':'CPP17','cpp.g++20':'CPP20','cpp.g++':'CPP17','python.3':'PYTHON3'};
export function importPolygon(files:Map<string,Buffer>,profiles:Profile[]):ImportResult{
 const xml=files.get('problem.xml');if(!xml)throw new PackageError('包根目录缺少 problem.xml');const root=readXml(xml),m=blankManifest(root.attrs['short-name']||'导入题目'),report:Issue[]=[],used=new Set<Xml>(),attrs=new Map<Xml,Set<string>>(),usedFiles=new Set(['problem.xml']);
 const add=(area:string,status:Issue['status'],message:string)=>report.push({area,status,message});
 const mark=(node:Xml|undefined,keys:string[]=[])=>{if(node){used.add(node);attrs.set(node,new Set([...(attrs.get(node)??[]),...keys]));}return node;};
 const nodes=(node:Xml|undefined,name:string)=>{mark(node);return(node?.children??[]).filter(n=>n.name===name);};
 const one=(node:Xml|undefined,name:string)=>{const found=nodes(node,name);if(found.length>1)throw new PackageError(`重复的 ${name} 元素`);return mark(found[0]);};
 const text=(node:Xml|undefined,name:string)=>one(node,name)?.text.trim();
 const bytes=(path:string)=>{safePath(path);const value=files.get(path);if(!value)throw new PackageError(`包内缺少 ${path}`);usedFiles.add(path);return value;};
 const utf8=(path:string)=>{try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes(path));}catch(e){if(e instanceof PackageError)throw e;throw new PackageError(`源码必须是 UTF-8：${path}`);}};
 const blob=(path:string):StoredBlob=>{const b=bytes(path);return{key:path,hash:digest(b),bytes:b.length};};
 const pattern=(p:string|undefined,n:number)=>{if(!p||!/%(?:0[1-6])?d/.test(p)||p.replace(/%(?:0[1-6])?d/,'').includes('%'))throw new PackageError('仅支持一个 %d / %02d 至 %06d 的相对路径模式');return safePath(p.replace(/%(?:0([1-6]))?d/,(_,w)=>String(n).padStart(Number(w??0),'0')));};
 mark(root,['short-name','revision','url']);const names=one(root,'names');for(const n of nodes(names,'name')){mark(n,['language','value']);if(n.attrs.language==='english'||m.meta.title===root.attrs['short-name'])m.meta.title=n.attrs.value;}
 const program=(node:Xml,role:ProgramRole,name?:string)=>{const s=one(node,'source');if(!s){add('programs','BLOCKED',`${role} 缺少可移植源码`);return undefined;}mark(s,['path','type']);const language=sourceTypes[s.attrs.type];const profile=profiles.find(p=>p.language===language);if(!profile){add('programs','BLOCKED',`不支持或缺少本地编译 profile：${s.attrs.type}`);return undefined;}
  const source=utf8(s.attrs.path),id=`p${m.programs.length+1}`;const p:ManifestProgram={id,revisionId:id+'r',version:1,name:(name||s.attrs.path).slice(0,120),role,source,sourceHash:digest(source),enabled:true,notes:'Polygon 离线导入',expectedVerdicts:role==='WRONG_SOLUTION'?['WA']:role==='TIME_LIMIT_SOLUTION'?['TLE']:['AC'],validatorScope:'GLOBAL',profile};m.programs.push(p);add(s.attrs.path,'MAPPED',`${role} → ${profile.name}；只保存源码，未执行`);if(s.attrs.type==='cpp.g++')add(s.attrs.path,'WARNING','旧 cpp.g++ 未指定 C++ 标准；本次明确使用本地 CPP17，请核对源码语义并重新验收');return p;
 };
 const assets=one(root,'assets'),solutions=one(assets,'solutions');for(const s of nodes(solutions,'solution')){mark(s,['tag']);const role:ProgramRole|undefined=({main:'MAIN_SOLUTION',accepted:'CORRECT_SOLUTION','wrong-answer':'WRONG_SOLUTION','time-limit-exceeded':'TIME_LIMIT_SOLUTION',slow:'BRUTE_FORCE'}as const)[s.attrs.tag as 'main'];if(!role){add('solutions','BLOCKED',`未支持的解法预期 ${s.attrs.tag}`);continue;}program(s,role);}
 for(const [tag,role]of [['checker','CHECKER'],['validator','VALIDATOR'],['interactor','INTERACTOR']] as const){const n=one(assets,tag);if(!n)continue;mark(n,['name','type']);if(n.attrs.type&&n.attrs.type!=='testlib')add(tag,'BLOCKED',`不支持工具协议 ${n.attrs.type}`);
  let p:ManifestProgram|undefined;if(tag==='checker'&&n.attrs.name==='std::wcmp.cpp'&&!n.children.some(c=>c.name==='source'))m.judgeSettings.checkerMode='TOKENS';else{p=program(n,role);if(tag==='checker')m.judgeSettings.checkerMode='CUSTOM';}
  if(tag==='interactor'){m.judgeSettings.interactionMode='INTERACTIVE';m.judgeSettings.interaction={...defaultInteractionSettings,verdictMode:assets?.children.some(c=>c.name==='checker')?'CHECKER':'DIRECT'};add('interaction','WARNING','交互器 argv 使用 input / tout / answer；资源与空闲限制采用本地默认值，必须核对并重新验收。');}
  const set=one(n,'testset');if(set){const tests=nodes(one(set,'tests'),'test'),count=Number(text(set,'test-count'));if(count!==tests.length)throw new PackageError('工具自测数量不匹配');const ip=text(set,'input-path-pattern'),ap=text(set,'answer-path-pattern'),op=text(set,'output-path-pattern');
   for(const [i,t]of tests.entries()){mark(t,['verdict']);const expected=({valid:'ACCEPT',invalid:'REJECT',ok:'AC','wrong-answer':'WA','presentation-error':'PE'} as const)[t.attrs.verdict as 'valid'];if(!expected||!p){add('selfTests','BLOCKED','工具自测判定或工具源码无法映射');continue;}const empty='pf-empty';if(!files.has(empty))files.set(empty,Buffer.alloc(0));usedFiles.add(empty);m.selfTests.push({id:`s${i}-${tag}`,version:1,name:`${tag} ${i+1}`,kind:tag==='validator'?'VALIDATOR':'CHECKER',programId:p.id,enabled:true,expected,input:blob(pattern(ip,i+1)),answer:blob(ap?pattern(ap,i+1):empty),output:blob(op?pattern(op,i+1):empty)});}
  }
 }
 const fileNode=one(root,'files'),executables=one(fileNode,'executables'),generators=new Map<string,ManifestProgram>();for(const e of nodes(executables,'executable')){mark(e);const p=program(e,'GENERATOR');if(p){const path=e.children.find(c=>c.name==='source')!.attrs.path;generators.set(path.split('/').at(-1)!.replace(/\.[^.]+$/,''),p);}}
 const judging=one(root,'judging');mark(judging,['input-file','output-file']);if(judging?.attrs['input-file']||judging?.attrs['output-file']){m.judgeSettings.ioMode='FILES';m.judgeSettings.inputFile=judging.attrs['input-file'];m.judgeSettings.outputFile=judging.attrs['output-file'];}
 const sets=nodes(judging,'testset');if(sets.length!==1||sets[0]?.attrs.name!=='tests')add('testsets','BLOCKED','只支持唯一的 tests 测试集');const set=mark(sets[0],['name']);
 if(set){const time=Number(text(set,'time-limit')),memory=Number(text(set,'memory-limit'))/1048576;m.judgeSettings.timeLimitMs=time;m.judgeSettings.memoryLimitMb=memory;
  const tests=nodes(one(set,'tests'),'test'),count=Number(text(set,'test-count'));if(count!==tests.length||count>200)throw new PackageError('测试数量不匹配或超过 200');const ip=text(set,'input-path-pattern'),ap=text(set,'answer-path-pattern');
  for(const [i,t]of tests.entries()){mark(t,['method','cmd','sample','group','points']);const inputPath=pattern(ip,i+1),answerPath=ap?pattern(ap,i+1):null;const group=t.attrs.group||'default';m.tests.push({id:`t${i+1}`,revisionId:`t${i+1}r`,version:1,number:i+1,groupName:group,isSample:t.attrs.sample==='true',enabled:true,notes:'',input:blob(inputPath),answer:answerPath&&files.has(answerPath)?blob(answerPath):null,provenance:null});
   if(t.attrs.points)add('groups','BLOCKED',`测试 ${i+1} 的逐测试 points 不在此计分子集中`);
   if(!['manual','generated'].includes(t.attrs.method))add('tests','BLOCKED',`测试 ${i+1} 的 method 未支持：${t.attrs.method}`);
   if(t.attrs.method==='generated'){const cmd=t.attrs.cmd??'';if(!/^[A-Za-z0-9_./=+,-]+(?: +[A-Za-z0-9_./=+,-]+)*$/.test(cmd)){add('generation','BLOCKED',`测试 ${i+1} 命令含 shell/引号/扩展语法，原文已隔离`);continue;}const [name,...argv]=cmd.split(/ +/),p=generators.get(name),seed=argv.pop();if(!p||!seed||!/^[-]?[0-9]{1,18}$/.test(seed)){add('generation','BLOCKED',`生成器 ${name} 未匹配或缺少末尾整数种子`);continue;}m.plans.push({id:`g${i+1}`,version:1,name:`Polygon test ${i+1}`,programId:p.id,enabled:false,argv,seed,count:1,numberStart:i+1,groupName:group,isSample:t.attrs.sample==='true'});add('generation','WARNING',`测试 ${i+1} 原命令映射为 argv + 末尾整数种子（计划停用，避免覆盖已有编号）；现有输入字节为准。`);}
  }
  const gs=one(set,'groups');if(gs){m.judgeSettings.scoringMode='PARTIAL';m.groups={groups:[]};for(const g of nodes(gs,'group')){mark(g,['name','points','points-policy','feedback-policy']);const deps=nodes(one(g,'dependencies'),'dependency').map(d=>{mark(d,['group']);return d.attrs.group;});const members=m.tests.filter(t=>t.groupName===g.attrs.name).map(t=>({testId:t.id,revisionId:t.revisionId,weight:1}));
   if(g.attrs['points-policy']!=='complete-group')add('groups','BLOCKED',`组 ${g.attrs.name} 仅支持 complete-group；each-test 等计分不可静默降级`);
   m.groups.groups.push({id:g.attrs.name,points:Number(g.attrs.points),aggregation:'ALL',members,dependencies:deps,extraValidatorIds:[]});if(g.attrs['feedback-policy'])add('groups','WARNING',`组 ${g.attrs.name} 的 feedback-policy 仅保留在 XML；本平台不提供比赛评测端反馈策略`);
  }add('groups','MAPPED','complete-group / 整组通过分值 / 依赖映射为 ALL 数据组；仍需本地验收。');}else if(tests.some(t=>t.attrs.points||t.attrs.group))add('groups','BLOCKED','存在组/逐测试分值但缺少可映射的完整分组定义');
 }
 const statements=one(root,'statements');for(const s of nodes(statements,'statement')){mark(s,['language','type','path']);const lang=languageNames[s.attrs.language]||s.attrs.language;if(!/^[a-z]{2}(-[A-Z]{2})?$/.test(lang)){add('statement','WARNING',`语言 ${s.attrs.language} 需手工转换，文件留在隔离包`);continue;}if(s.attrs.type!=='application/x-tex'){add('statement','WARNING',`${s.attrs.path} 为 ${s.attrs.type}，保留原文件，未转换为作者正文`);continue;}
  m.documents.push({id:`d${m.documents.length+1}`,revisionId:`d${m.documents.length+1}r`,version:1,language:lang,kind:'STATEMENT',enabled:true,body:utf8(s.attrs.path),metadata:{title:m.meta.title,author:''},sampleRevisionIds:m.tests.filter(t=>t.isSample&&t.answer).slice(0,10).map(t=>t.revisionId),template:null});}
 m.samples=m.tests.filter(t=>m.documents.some(d=>d.sampleRevisionIds.includes(t.revisionId))).map(t=>structuredClone(t));
 // Every unconsumed XML field is reported. Unknown judging/program semantics block import.
 const walk=(n:Xml,path:string)=>{if(!used.has(n)){add(path,/^problem\/(statements|files\/resources|tags|properties|names)/.test(path)||['binary','copy'].includes(n.name)?'WARNING':'BLOCKED','未转换的 XML 节点；原文保存在隔离包');return;}for(const key of Object.keys(n.attrs))if(!attrs.get(n)?.has(key))add(path+'/@'+key,'BLOCKED','未支持的属性；请核对其语义');for(const c of n.children)walk(c,path+'/'+c.name);};walk(root,'problem');
 for(const path of files.keys())if(!usedFiles.has(path))add(path,'WARNING','未使用文件保留在隔离包；不会执行、编译或导入为管理员模板');
 add('templates','WARNING','所有题面必须显式绑定当地管理员发布的模板；外部 TeX 导言、样式、脚本不作为模板导入。');return{manifest:m,report};
}
export const polygonExporter:Exporter={id:'POLYGON',async export(source,purpose,read){
 const m=selectManifest(source,purpose),files=new Map<string,Buffer>(),report:Issue[]=[{area:'compatibility',status:'WARNING',message:'Polygon problem.xml 离线明确子集；未向外部 Polygon/OJ 上传验证。扩展信息单独保存于 compatibility.json。'}];
 const add=(area:string,message:string)=>report.push({area,status:'BLOCKED',message});const put=(path:string,text:string)=>files.set(path,Buffer.from(text));
 const blob=async(path:string,b:StoredBlob)=>{const bytes=await read(b.key);if(digest(bytes)!==b.hash||bytes.length!==b.bytes)throw new PackageError('固定资源哈希不匹配');files.set(path,bytes);};
 const types={CPP17:'cpp.g++17',CPP20:'cpp.g++20',PYTHON3:'python.3'},paths=new Map<string,string>();
 for(const [i,p]of m.programs.entries()){const path=`files/p${i+1}.${p.profile.language==='PYTHON3'?'py':'cpp'}`;paths.set(p.id,path);put(path,p.source);if(p.expectedScore)add('expectations',`${p.name} 的分数范围保留在兼容报告，Polygon 预期标签不等价`);}
 const sourceXml=(p:ManifestProgram)=>`<source path="${paths.get(p.id)}" type="${types[p.profile.language]}"/>`;
 const solutions=m.programs.filter(p=>['MAIN_SOLUTION','CORRECT_SOLUTION','WRONG_SOLUTION','TIME_LIMIT_SOLUTION','BRUTE_FORCE'].includes(p.role)).map(p=>`<solution tag="${({MAIN_SOLUTION:'main',CORRECT_SOLUTION:'accepted',WRONG_SOLUTION:'wrong-answer',TIME_LIMIT_SOLUTION:'time-limit-exceeded',BRUTE_FORCE:'slow'}as Record<string,string>)[p.role]}">${sourceXml(p)}</solution>`).join('');
 const tools=m.programs.filter(p=>['CHECKER','VALIDATOR','INTERACTOR'].includes(p.role)).map(p=>`<${p.role.toLowerCase()} type="testlib">${sourceXml(p)}</${p.role.toLowerCase()}>`).join('');
 const generators=m.programs.filter(p=>p.role==='GENERATOR').map(p=>`<executable>${sourceXml(p)}</executable>`).join('');
 const statements:string[]=[];for(const [i,d]of m.documents.entries()){const path=`statements/${d.language}/${d.kind.toLowerCase()}-${i}.tex`;put(path,d.body);if(d.kind==='STATEMENT')statements.push(`<statement language="${x(Object.entries(languageNames).find(([,v])=>v===d.language)?.[0]??d.language)}" type="application/x-tex" path="${path}"/>`);else report.push({area:'editorials',status:'WARNING',message:`${d.kind} ${d.language} 保留为独立 TeX 附件，不冒充 Polygon 题面或系统模板。`});}
 for(const a of m.assets)await blob(a.path,a.blob);
 const tests=purpose==='STATEMENT'?m.samples:m.tests.filter(t=>t.enabled);let testXml='';for(const [i,t]of tests.entries()){const n=String(i+1).padStart(3,'0');await blob(`tests/${n}`,t.input);if(t.answer)await blob(`tests/${n}.a`,t.answer);else if(m.judgeSettings.interactionMode==='BATCH')add('answers',`测试 ${t.number} 未收集答案，不能作为完整评测包`);testXml+=`<test method="manual" sample="${t.isSample}"${m.groups?.groups.length?` group="${x(m.groups.groups.find(g=>g.members.some(tg=>tg.revisionId===t.revisionId))?.id??t.groupName)}"`:''}/>`;}
 let groups='';if(m.groups?.groups.length){groups='<groups>'+m.groups.groups.map(g=>{if(g.aggregation!=='ALL'||g.extraValidatorIds.length)add('groups',`组 ${g.id} 的权重/额外 Validator 不在 Polygon 子集中`);return`<group name="${x(g.id)}" points="${g.points}" points-policy="complete-group"><dependencies>${g.dependencies.map(d=>`<dependency group="${x(d)}"/>`).join('')}</dependencies></group>`;}).join('')+'</groups>';}
 if(m.programs.some(p=>p.role==='EXTRA_VALIDATOR'))add('validators','额外 Validator 的适用范围不能转换到单 Validator 字段');
 if(m.judgeSettings.checkerMode!=='CUSTOM'&&['FULL','DATA'].includes(purpose)&&m.judgeSettings.checkerMode!=='TOKENS')add('checker','EXACT / FLOAT 的字节与容差语义不能自动替换成 Polygon 标准 Checker');
 if(m.plans.length)add('generation','PF_SEED 环境变量约定不等价于 Polygon cmd；计划完整保留于 compatibility.json，数据已按快照导出');
 if(m.selfTests.length)add('selfTests','本轮导出未转换工具自测，原生包可保留完整记录');
 if(m.stress)add('stress','有预算对拍配置没有等价的 Polygon 字段');
 if(m.judgeSettings.interactionMode==='INTERACTIVE')add('interaction','交互的直接/Checker 模式、墙钟/空闲/输出限制需要目标平台人工核对');
 if(purpose!=='FULL'&&purpose!=='DATA')report.push({area:'purpose',status:'WARNING',message:`${purpose} 资料子集不是完整可评测题包`});
 const j=m.judgeSettings,checker=j.checkerMode==='TOKENS'&&['DATA','FULL'].includes(purpose)?'<checker name="std::wcmp.cpp" type="testlib"/>':'';
 put('problem.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<problem short-name="problemforge-export"><names><name language="english" value="${x(m.meta.title)}"/></names><statements>${statements.join('')}</statements><judging input-file="${j.ioMode==='FILES'?x(j.inputFile):''}" output-file="${j.ioMode==='FILES'?x(j.outputFile):''}"><testset name="tests"><time-limit>${j.timeLimitMs}</time-limit><memory-limit>${j.memoryLimitMb*1048576}</memory-limit><test-count>${tests.length}</test-count><input-path-pattern>tests/%03d</input-path-pattern><answer-path-pattern>tests/%03d.a</answer-path-pattern><tests>${testXml}</tests>${groups}</testset></judging><files><executables>${generators}</executables></files><assets><solutions>${solutions}</solutions>${tools}${checker}</assets></problem>`);
 // Purpose-filtered supplements never contain storage keys or files from another purpose.
 put('compatibility.json',JSON.stringify({format:'problemforge-polygon-subset-v1',purpose,report,plans:m.plans,settings:['DATA','FULL'].includes(purpose)?m.judgeSettings:null,groups:m.groups,expectations:m.programs.filter(p=>p.expectedScore).map(p=>({path:paths.get(p.id),expectedScore:p.expectedScore})),documents:m.documents.map(d=>({kind:d.kind,language:d.language,template:d.template,sampleRevisionIds:d.sampleRevisionIds})),sampleNote:'原生格式支持完整样例引用；本文件不声明样例宏已在其他平台展开'},null,2));
 return{files,report};
}};
