<script setup lang="ts">
import{ref,onMounted,computed}from'vue';import{NSelect,NButton,NTag,NAlert,useMessage,useDialog}from'naive-ui';import{api}from'../api';
const props=defineProps<{scope:'problems'|'contests';id:string;owner:boolean}>(),message=useMessage(),dialog=useDialog();
const revisions=ref<any[]>([]),exports=ref<any[]>([]),releases=ref<any[]>([]),revisionId=ref<string|null>(null),purpose=ref('STATEMENT'),format=ref('NATIVE'),busy=ref(false),selected=ref<any>();
const purposes=[{label:'题面（含引用样例与图片）',value:'STATEMENT'},{label:'文档题解',value:'EDITORIAL_DOCUMENT'},{label:'Beamer 题解',value:'EDITORIAL_BEAMER'},{label:'正式数据与判题工具',value:'DATA'},{label:'参考解源码',value:'REFERENCE'},{label:'完整题目包',value:'FULL'}];
const blocked=computed(()=>selected.value?.report.some((r:any)=>r.status==='BLOCKED'));
async function act(fn:()=>Promise<void>){busy.value=true;try{await fn();}catch(e){message.error((e as Error).message);}finally{busy.value=false;}}
async function load(){revisions.value=props.scope==='contests'?(await api(`/contests/${props.id}`)).revisions:await api(`/problems/${props.id}/revisions`);exports.value=await api(`/${props.scope}/${props.id}/exports`);releases.value=await api(`/${props.scope}/${props.id}/releases`);if(!revisionId.value)revisionId.value=revisions.value[0]?.id??null;}
onMounted(()=>act(load));
async function generate(){await act(async()=>{selected.value=await api(`/${props.scope}/${props.id}/exports`,{method:'POST',body:JSON.stringify({revisionId:revisionId.value,purpose:purpose.value,format:format.value})});await load();message.success('题包已生成，查看兼容报告后下载');});}
function publish(){dialog.warning({title:'发布所选用途的题包',content:`将创建无需登录即可下载的链接，内容为 ${purposes.find(p=>p.value===selected.value.purpose)?.label}。撤回能禁止新的平台下载，已下载文件不能追回。`,positiveText:'发布此题包',negativeText:'返回',onPositiveClick:()=>act(async()=>{await api(`/${props.scope}/${props.id}/releases`,{method:'POST',body:JSON.stringify({exportId:selected.value.id})});await load();})});}
async function revoke(id:string){await act(async()=>{await api(`/releases/${id}/revoke`,{method:'POST'});await load();});}
</script>
<template><div class="p4-editor"><p>按用途选择固定修订。原生完整包用于工作副本往返；Polygon 为离线子集，兼容报告逐项列出需处理内容。</p><div class="p4-toolbar"><NSelect v-model:value="revisionId" :options="revisions.map(r=>({label:`#${r.number} ${r.label??''}${r.current?' · 当前':''}`,value:r.id}))" placeholder="先保存修订 / 冻结比赛"/><NSelect v-model:value="purpose" :options="purposes"/><NSelect v-model:value="format" :options="[{label:'ProblemForge 原生 v1',value:'NATIVE'},{label:'Polygon 离线子集',value:'POLYGON'}]"/><NButton type="primary" :loading="busy" :disabled="!revisionId" @click="generate">生成题包</NButton><NButton @click="act(load)">刷新</NButton></div><NAlert v-if="scope==='problems'" type="info">正式发布需要当前工作副本对应的已冻结修订。未冻结修订可以先导出检查。</NAlert><div class="p4-split"><aside class="p4-list"><NButton v-for="e in exports" :key="e.id" :type="selected?.id===e.id?'primary':'default'" @click="selected=e">{{e.format}} · {{purposes.find(p=>p.value===e.purpose)?.label}}<br/>{{new Date(e.createdAt).toLocaleString('zh-CN')}}</NButton></aside><section v-if="selected"><h3>导出报告</h3><p>{{selected.bytes.toLocaleString()}} 字节 · SHA-256<br/><code>{{selected.hash}}</code></p><div v-for="(r,i) in selected.report" :key="i" class="p4-comment"><NTag :type="r.status==='BLOCKED'?'error':r.status==='WARNING'?'warning':'success'">{{r.status==='BLOCKED'?'待处理':r.status==='WARNING'?'注意':'已映射'}}</NTag> {{r.area}}<p>{{r.message}}</p></div><div class="p4-toolbar"><a class="download-link" :href="`/api/exports/${selected.id}/file`">下载私有题包</a><NButton v-if="owner" :disabled="blocked" @click="publish">公开发布此用途</NButton></div><NAlert v-if="blocked" type="warning">判题语义存在未解决项，此包只供私下处理，不能正式发布。</NAlert></section></div><h3>已发布题包</h3><div v-for="r in releases.filter(r=>r.exportId)" :key="r.id" class="publication-row"><NTag>{{purposes.find(p=>p.value===r.purpose)?.label}}</NTag><span>{{r.revokedAt?'已撤回':'已发布'}}</span><a v-if="!r.revokedAt" :href="`/api/released/${r.token}/file`">下载</a><NButton v-if="owner&&!r.revokedAt" size="small" @click="revoke(r.id)">撤回</NButton></div></div></template>
