<script setup lang="ts">
import{ref,onMounted,computed}from'vue';import{useRouter}from'vue-router';
import{NButton,NInput,NSelect,NSwitch,NTag,NAlert,NFormItem,NTabs,NTab,NEmpty,useMessage,useDialog}from'naive-ui';
import{api}from'../api';import MemberPanel from'./MemberPanel.vue';
import PackagePanel from'./PackagePanel.vue';
const props=defineProps<{problem:any;hasUnsaved:boolean}>();const emit=defineEmits<{dirty:[boolean];metadata:[any];restored:[]}>();
const message=useMessage(),dialog=useDialog(),router=useRouter(),tab=ref('overview');const meta=ref<any>({}),tagText=ref(''),directory=ref<any>({users:[]}),revisions=ref<any[]>([]),working=ref<any>(),selected=ref<any>(),diff=ref<any[]>([]),label=ref(''),comment=ref(''),anchor=ref(''),reviewMessage=ref(''),busy=ref(false);
const canEdit=computed(()=>['OWNER','EDITOR'].includes(props.problem.role)&&!props.problem.archived),canReview=computed(()=>['OWNER','REVIEWER'].includes(props.problem.role));
const stateLabels:Record<string,string>={DRAFT:'草稿修订',SUBMITTED:'待审核',CHANGES_REQUESTED:'要求修改',APPROVED:'已批准',FROZEN:'已冻结'};
onMounted(async()=>{meta.value={expectedVersion:props.problem.version,title:props.problem.title,notes:props.problem.notes,responsibleId:props.problem.responsibleId,archived:props.problem.archived};tagText.value=props.problem.tags.join(', ');directory.value=await api('/directory');await refresh();});
function changed(){emit('dirty',true);}
async function act(action:()=>Promise<void>){busy.value=true;try{await action();}catch(e){message.error((e as Error).message);}finally{busy.value=false;}}
async function refresh(){try{working.value=await api(`/problems/${props.problem.id}/working-revision`);revisions.value=await api(`/problems/${props.problem.id}/revisions`);if(selected.value)await inspect(selected.value.id);}catch(e){message.error((e as Error).message);}}
async function saveMeta(){await act(async()=>{const result=await api(`/problems/${props.problem.id}/meta`,{method:'PUT',body:JSON.stringify({...meta.value,tags:tagText.value.split(/[,，]+/).map(v=>v.trim()).filter(Boolean)})});meta.value.expectedVersion=result.version;emit('metadata',result);emit('dirty',false);await refresh();message.success('题目元信息已保存');});}
async function copy(){await act(async()=>{const p=await api(`/problems/${props.problem.id}/copy`,{method:'POST',body:JSON.stringify({title:props.problem.title+'（副本）'})});await router.push(`/problems/${p.id}`);});}
async function createRevision(){await act(async()=>{const r=await api(`/problems/${props.problem.id}/revisions`,{method:'POST',body:JSON.stringify({expectedHash:working.value.hash,label:label.value})});label.value='';await refresh();await inspect(r.id);message.success('不可变修订已保存');});}
async function inspect(id:string){selected.value=await api(`/revisions/${id}`);diff.value=await api(`/revisions/${id}/diff`);}
async function review(action:string){await act(async()=>{await api(`/revisions/${selected.value.id}/review`,{method:'POST',body:JSON.stringify({action,message:reviewMessage.value})});reviewMessage.value='';await refresh();});}
async function addComment(){await act(async()=>{await api(`/revisions/${selected.value.id}/comments`,{method:'POST',body:JSON.stringify({body:comment.value,anchor:anchor.value})});comment.value='';await inspect(selected.value.id);});}
async function resolve(id:string,resolved:boolean){await act(async()=>{await api(`/review-comments/${id}`,{method:'PUT',body:JSON.stringify({resolved})});await inspect(selected.value.id);});}
function restore(){dialog.warning({title:'从选中修订恢复工作副本',content:'将追加稿件、程序和数据的新版本，并建立新的待审核修订。历史和已冻结清单保留，当前验收需要重新执行。',positiveText:'恢复并创建新修订',negativeText:'返回',onPositiveClick:()=>act(async()=>{await api(`/revisions/${selected.value.id}/restore`,{method:'POST',body:JSON.stringify({expectedHash:working.value.hash,label:`恢复自修订 ${selected.value.number}`})});await refresh();emit('restored');})});}
</script>
<template><div class="panel p4-panel"><NTabs v-model:value="tab"><NTab name="overview">概览与组织</NTab><NTab name="revisions">修订与审核</NTab><NTab name="packages">题包与发布</NTab><NTab name="members">成员与权限</NTab></NTabs>
<div v-if="tab==='overview'" class="p4-editor"><div class="p4-form-row"><NFormItem label="题目名称"><NInput v-model:value="meta.title" :disabled="!canEdit" @update:value="changed"/></NFormItem><NFormItem label="标签，逗号分隔"><NInput v-model:value="tagText" :disabled="!canEdit" @update:value="changed"/></NFormItem><NFormItem label="负责出题人"><NSelect v-model:value="meta.responsibleId" clearable filterable :disabled="!canEdit" :options="directory.users.map((u:any)=>({label:u.name,value:u.id}))" @update:value="changed"/></NFormItem></div><NFormItem label="内部备注"><NInput v-model:value="meta.notes" type="textarea" :disabled="!canEdit" @update:value="changed"/></NFormItem><div class="panel-toolbar"><label><NSwitch v-model:value="meta.archived" :disabled="problem.role!=='OWNER'" @update:value="changed"/> 归档（保留历史与产物）</label><NButton type="primary" :loading="busy" :disabled="!['OWNER','EDITOR'].includes(problem.role)" @click="saveMeta">保存元信息</NButton><NButton :disabled="hasUnsaved||busy" @click="copy">复制为我的私有题目</NButton></div></div>
<template v-else-if="tab==='revisions'"><div class="panel-toolbar"><NInput v-model:value="label" placeholder="修订说明，如：审题前完整版本" style="max-width:380px"/><NButton type="primary" :disabled="!canEdit||!label.trim()||hasUnsaved" :loading="busy" @click="createRevision">保存当前工作副本为修订</NButton><NButton @click="refresh">刷新清单与差异</NButton><NTag v-if="working">{{working.acceptanceRunId?'当前判题依赖已验收':'当前依赖尚无成功验收'}}</NTag></div><NAlert v-if="hasUnsaved" type="warning">请先保存其他分区的编辑，再建立或恢复修订。</NAlert>
<div class="p4-split"><aside class="p4-list"><NButton v-for="r in revisions" :key="r.id" block :type="selected?.id===r.id?'primary':'default'" @click="inspect(r.id)">#{{r.number}} {{r.label}}</NButton><NEmpty v-if="!revisions.length" description="尚无整题修订"/></aside><section v-if="selected" class="p4-detail"><div class="panel-toolbar"><strong>修订 #{{selected.number}} · {{selected.label}}</strong><NTag>{{stateLabels[selected.state]}}</NTag><NTag v-if="revisions.find(r=>r.id===selected.id)?.reviewStale" type="warning">审核依赖已过期</NTag></div><p class="muted">清单 {{selected.hash}}<br/>工作副本继续编辑不会改变本清单；冻结与正式发布使用固定修订。</p>
<NInput v-model:value="reviewMessage" placeholder="审核意见（可选）"/><div class="panel-toolbar"><NButton v-if="canEdit&&['DRAFT','CHANGES_REQUESTED'].includes(selected.state)" @click="review('SUBMIT')">提交审核</NButton><template v-if="canReview&&selected.state==='SUBMITTED'"><NButton type="primary" @click="review('APPROVE')">批准本修订</NButton><NButton @click="review('REQUEST_CHANGES')">要求修改</NButton></template><NButton v-if="problem.role==='OWNER'&&selected.state==='APPROVED'" type="primary" @click="review('FREEZE')">检查验收并冻结</NButton><NButton :disabled="!canEdit||hasUnsaved" @click="restore">恢复为新修订</NButton></div>
<details><summary>与当前工作副本比较 · {{diff.length}} 项变化</summary><div v-for="item in diff" :key="item.path"><strong>{{item.path}}</strong><div class="p4-diff"><pre>{{JSON.stringify(item.before,null,2)}}</pre><pre>{{JSON.stringify(item.after,null,2)}}</pre></div></div><p v-if="!diff.length">当前工作副本与本清单一致。</p></details><details><summary>审核记录</summary><p v-for="d in selected.decisions" :key="d.id">{{d.action}} · {{new Date(d.createdAt).toLocaleString('zh-CN')}}<br/>{{d.message}}</p></details>
<h3>修订评论</h3><div v-for="c in selected.comments" :key="c.id" class="p4-comment"><NTag size="small">{{c.resolved?'已解决':'未解决'}}</NTag> {{c.anchor}}<p>{{c.body}}</p><NButton v-if="problem.role!=='VIEWER'" size="small" @click="resolve(c.id,!c.resolved)">{{c.resolved?'重新打开':'标记解决'}}</NButton></div><template v-if="problem.role!=='VIEWER'"><NInput v-model:value="anchor" placeholder="关联位置，如：题面第 12 行 / 数据组 g20"/><NInput v-model:value="comment" type="textarea" placeholder="评论固定在本修订"/><NButton :disabled="!comment.trim()" @click="addComment">添加评论</NButton></template></section></div></template>
<PackagePanel v-else-if="tab==='packages'" scope="problems" :id="problem.id" :owner="problem.role==='OWNER'"/>
<MemberPanel v-else scope="problems" :id="problem.id" :owner="problem.role==='OWNER'"/>
</div></template>
