import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { Client } from './http-client.ts';
const f=JSON.parse(await readFile('.local/verify-p2-fixture.json','utf8')),c=new Client();await c.login(f.authorEmail,f.authorPassword);
const profiles=await c.call('/compile-profiles'),p=await c.call('/problems','POST',{title:`P3 20/30/50 分组验证 · ${Date.now()}`,language:'zh-CN'});
const program=(name:string,role:string,source:string,language='PYTHON3',extra={})=>c.call(`/problems/${p.id}/programs`,'POST',{name,role,source,profileId:profiles.find((p:any)=>p.language===language).id,expectedVerdicts:[role==='WRONG_SOLUTION'?'WA':'AC'],notes:'',enabled:true,...extra});
const main=await program('满分主标程','MAIN_SOLUTION','a,b=map(int,input().split())\nprint(a+b)');
await program('全局 Validator','VALIDATOR',await readFile('fixtures/judge/sum-validator.cpp','utf8'),'CPP17');
const extra=await program('只允许小输入','EXTRA_VALIDATOR','#include "testlib.h"\nint main(int argc,char**argv){registerValidation(argc,argv);inf.readInt(1,2);inf.readSpace();inf.readInt(1,100);inf.readEoln();inf.readEof();}','CPP17',{validatorScope:'GROUPS'});
const tests=[];
for(let i=1;i<=4;i++)tests.push(await c.call(`/problems/${p.id}/tests`,'POST',{number:i,groupName:i===1?'small':i===4?'large':'middle',isSample:false,notes:'',enabled:true,inputBase64:Buffer.from(`${i} 1\n`).toString('base64'),answerBase64:null}));
const member=(i:number)=>({testId:tests[i-1].id,revisionId:tests[i-1].currentRevision.id,weight:1});
const groups=[{id:'g20',points:20,aggregation:'ALL',members:[member(1)],dependencies:[],extraValidatorIds:[extra.id]},{id:'g30',points:30,aggregation:'WEIGHTED',members:[member(2),member(3)],dependencies:['g20'],extraValidatorIds:[]},{id:'g50',points:50,aggregation:'ALL',members:[member(4)],dependencies:['g30'],extraValidatorIds:[]}];
let config=await c.call(`/problems/${p.id}/test-groups`,'PUT',{expectedVersion:0,data:{groups}});
await c.call(`/problems/${p.id}/test-groups`,'PUT',{expectedVersion:config.version,data:{groups:groups.map((g,i)=>i===0?{...g,dependencies:['g50']}:g)}},422);
const partial=await program('35 分解法','WRONG_SOLUTION','a,b=map(int,input().split())\nprint(a+b if a!=3 else 0)','PYTHON3',{expectedScore:{total:{min:35,max:35},groups:[{groupId:'g30',min:15,max:15},{groupId:'g50',min:0,max:0}]}});
const blocked=await program('前置失败后全部阻断','WRONG_SOLUTION','a,b=map(int,input().split())\nprint(a+b if a!=1 else 0)','PYTHON3',{expectedScore:{total:{min:0,max:0},groups:[]}});
const settings=await c.call(`/problems/${p.id}/judge-settings`);
await c.call(`/problems/${p.id}/judge-settings`,'PUT',{expectedVersion:settings.version,settings:{...settings.settings,scoringMode:'PARTIAL'}});
const submit=(purpose='ACCEPTANCE')=>c.call(`/problems/${p.id}/test-runs`,'POST',{purpose,requestKey:randomUUID()});
const run=await c.waitRun((await submit()).id);assert.equal(run.state,'SUCCEEDED',run.log);assert.equal(run.accepted,true,JSON.stringify(run.report));
const scores=run.report.scores;
assert.equal(scores.find((s:any)=>s.programId===main.id).totalScoreMilli,100000);
const part=scores.find((s:any)=>s.programId===partial.id);assert.equal(part.totalScoreMilli,35000);assert.deepEqual(part.groups.map((g:any)=>[g.rawScoreMilli,g.scoreMilli]),[[20000,20000],[15000,15000],[50000,0]]);assert.deepEqual(part.groups[2].blockedBy,['g30']);
const block=scores.find((s:any)=>s.programId===blocked.id);assert.equal(block.totalScoreMilli,0);assert.equal(block.groups[1].rawScoreMilli,30000);assert.deepEqual(block.groups[2].blockedBy,['g30']);
assert.equal(run.invocations.filter((i:any)=>i.programId===extra.id&&i.phase==='VALIDATOR').length,1);
assert.equal(run.currentValid,true);
config=await c.call(`/problems/${p.id}/test-groups`,'PUT',{expectedVersion:config.version,data:{groups:groups.map((g,i)=>i===2?{...g,extraValidatorIds:[extra.id]}:g)}});
assert.equal((await c.call(`/test-runs/${run.id}`)).stale,true);
const rejected=await c.waitRun((await submit('VALIDATE')).id);assert.equal(rejected.state,'FAILED');assert.equal(rejected.errorCode,'INVALID_INPUT');assert.equal(rejected.cases.find((t:any)=>t.number===4).validation,'REJECT');
// Restore a usable, explicit group configuration, then verify the fresh report.
config=await c.call(`/problems/${p.id}/test-groups`,'PUT',{expectedVersion:config.version,data:{groups}});
const current=await c.waitRun((await submit()).id);assert.equal(current.currentValid,true,current.log);
await writeFile('.local/verify-p3-groups.json',JSON.stringify({problemId:p.id,runId:run.id,currentRunId:current.id,rejectedRunId:rejected.id,scores,checks:['100/35/0 hand computed','weighted raw vs blocked score','transitive dependency block','cycle rejected','group validator only applies to group','group validator rejection','configuration stales report']},null,2));
console.log('PASS 20/30/50 scoring gives 100/35/0; DAG rejection, scoped validation, dependency blocking and stale results.');process.exit(0);
