import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { Client } from './http-client.ts';
const f = JSON.parse(await readFile('.local/verify-p2-fixture.json', 'utf8')), c = new Client();
await c.login(f.authorEmail, f.authorPassword);
const profiles = await c.call('/compile-profiles');
const p = await c.call('/problems', 'POST', { title: `P3 对拍验证 · ${Date.now()}`, language: 'zh-CN' });
async function program(name: string, role: string, source: string, language = 'PYTHON3') {
  return c.call(`/problems/${p.id}/programs`, 'POST', { name, role, source, profileId: profiles.find((p: any) => p.language === language).id, expectedVerdicts: [role === 'WRONG_SOLUTION' ? 'WA' : 'AC'], notes: '', enabled: true });
}
const generator = await program('固定种子生成器', 'GENERATOR', await readFile('fixtures/judge/sum-generator.py', 'utf8'));
const reference = await program('参考求和', 'MAIN_SOLUTION', 'a,b=map(int,input().split())\nprint(a+b)');
const candidate = await program('错误输出零', 'WRONG_SOLUTION', 'print(0)');
await program('输入校验', 'VALIDATOR', await readFile('fixtures/judge/sum-validator.cpp', 'utf8'), 'CPP17');
const data = { generatorId: generator.id, referenceId: reference.id, candidateId: candidate.id, checkerId: null, argv: ['100'], seed: '20260930', iterations: 20, budgetMs: 60000, stop: 'FIRST_COUNTEREXAMPLE' };
let config = await c.call(`/problems/${p.id}/stress-config`, 'PUT', { expectedVersion: 0, data });
await c.call(`/problems/${p.id}/stress-config`, 'PUT', { expectedVersion: 0, data }, 409);
const start = () => c.call(`/problems/${p.id}/test-runs`, 'POST', { purpose: 'STRESS', requestKey: randomUUID() });
const found = await c.waitRun((await start()).id);
assert.equal(found.state, 'SUCCEEDED', found.log); assert.equal(found.report.stress.outcome, 'COUNTEREXAMPLE_FOUND');
assert.equal(found.report.stress.completedIterations, 1); assert.equal(found.cases[0].origin.verdict, 'WA');
const counter = found.cases[0], bytes = await c.bytes(`/test-runs/${found.id}/cases/${counter.id}/input`);
const replay = await c.waitRun((await c.call(`/test-runs/${found.id}/cases/${counter.id}/reproduce`, 'POST', { requestKey: randomUUID(), regenerate: true })).id);
assert.equal(replay.report.stress.outcome, 'REPRODUCED', replay.log); assert.deepEqual(await c.bytes(`/test-runs/${replay.id}/cases/${replay.cases[0].id}/input`), bytes);
const applied = await c.call(`/test-runs/${found.id}/cases/${counter.id}/apply-counterexample`, 'POST', { number: 1, groupName: 'main', allowDuplicate: false });
assert.equal(applied.version, 1); assert.equal(applied.currentRevision.inputHash, counter.inputHash);
await c.call(`/test-runs/${found.id}/cases/${counter.id}/apply-counterexample`, 'POST', { number: 2, groupName: 'main', allowDuplicate: false }, 409);
await new Client().call(`/test-runs/${found.id}/cases/${counter.id}/input`, 'GET', undefined, 401);
config = await c.call(`/problems/${p.id}/stress-config`, 'PUT', { expectedVersion: config.version, data: { ...data, seed: '2' } });
assert.equal((await c.call(`/test-runs/${found.id}`)).stale, true);
await c.call(`/test-runs/${found.id}/cases/${counter.id}/apply-counterexample`, 'POST', { number: 2, groupName: 'main', allowDuplicate: true }, 409);
console.log('PASS counterexample, saved-input reproduction, explicit data revision, CAS, private access, stale rejection.');
const slow = await program('首轮后等待的生成器', 'GENERATOR', 'import sys\nif sys.argv[-1]=="1": print("1 2")\nelse:\n while True: pass');
config = await c.call(`/problems/${p.id}/stress-config`, 'PUT', { expectedVersion: config.version, data: { ...data, generatorId: slow.id, seed: '1', stop: 'CONTINUE' } });
const running = await start(); let progress: any;
const deadline = Date.now() + 60000;
while (Date.now() < deadline) {
  progress = await c.call(`/test-runs/${running.id}`);
  if (progress.report?.stress?.completedIterations >= 1) break;
  assert(!['FAILED', 'CANCELED', 'SUCCEEDED'].includes(progress.state), progress.log);
  await new Promise(r => setTimeout(r, 100));
}
assert.equal(progress.state, 'RUNNING'); await new Promise(r => setTimeout(r, 100));
const cancelAt = Date.now(); await c.call(`/test-runs/${running.id}/cancel`, 'POST');
const canceled = await c.waitRun(running.id, 15000); assert.equal(canceled.state, 'CANCELED'); assert.equal(canceled.report.stress.outcome, 'CANCELED'); assert(canceled.cases.length >= 1); assert(canceled.invocations.some((i: any) => i.verdict === 'CANCELED'));
const cancelElapsedMs = Date.now() - cancelAt;
config = await c.call(`/problems/${p.id}/stress-config`, 'PUT', { expectedVersion: config.version, data: { ...data, candidateId: reference.id, referenceId: (await program('独立正确参考', 'CORRECT_SOLUTION', 'a,b=map(int,input().split())\nprint(a+b)')).id, iterations: 1 } });
const completed = await c.waitRun((await start()).id); assert.equal(completed.report.stress.outcome, 'ITERATION_LIMIT', completed.log); assert.equal(completed.report.stress.counterexamples, 0);
// A multi-answer task must compare by its selected Checker, never by bytes.
const spj = await c.call('/problems', 'POST', { title: 'P3 多解对拍与预算 · ' + Date.now(), language: 'zh-CN' });
const sp = async (name: string, role: string, source: string, language = 'PYTHON3') => c.call('/problems/' + spj.id + '/programs', 'POST', { name, role, source, profileId: profiles.find((p: any) => p.language === language).id, expectedVerdicts: ['AC'], notes: '', enabled: true });
const sg = await sp('单数生成器', 'GENERATOR', 'print(10)');
const sr = await sp('参考拆分', 'MAIN_SOLUTION', 'n=int(input())\nprint(n,0)');
const sc = await sp('另一合法拆分', 'CORRECT_SOLUTION', await readFile('fixtures/judge/split-correct.py', 'utf8'));
const checker = await sp('合法性 Checker', 'CHECKER', await readFile('fixtures/judge/split-checker.cpp', 'utf8'), 'CPP17');
await sp('拆分 Validator', 'VALIDATOR', await readFile('fixtures/judge/split-validator.cpp', 'utf8'), 'CPP17');
const ss = await c.call('/problems/' + spj.id + '/judge-settings');
await c.call('/problems/' + spj.id + '/judge-settings', 'PUT', { expectedVersion: ss.version, settings: { ...ss.settings, checkerMode: 'CUSTOM' } });
const spjData = { ...data, generatorId: sg.id, referenceId: sr.id, candidateId: sc.id, checkerId: checker.id, argv: [], iterations: 1 };
await c.call('/problems/' + spj.id + '/stress-config', 'PUT', { expectedVersion: 0, data: spjData });
const multi = await c.waitRun((await c.call('/problems/' + spj.id + '/test-runs', 'POST', { purpose: 'STRESS', requestKey: randomUUID() })).id);
assert.equal(multi.report.stress.outcome, 'ITERATION_LIMIT', multi.log);
const mr = multi.invocations.find((i: any) => i.phase === 'MAIN_SOLUTION'), mc = multi.invocations.find((i: any) => i.phase === 'SOLUTION');
assert.notDeepEqual(await c.bytes('/invocations/' + mr.id + '/output'), await c.bytes('/invocations/' + mc.id + '/output')); assert.equal(mc.verdict, 'AC');
await c.call('/problems/' + spj.id + '/stress-config', 'PUT', { expectedVersion: 1, data: { ...spjData, budgetMs: 1000 } });
const budget = await c.waitRun((await c.call('/problems/' + spj.id + '/test-runs', 'POST', { purpose: 'STRESS', requestKey: randomUUID() })).id);
assert.equal(budget.state, 'FAILED'); assert.equal(budget.errorCode, 'TASK_BUDGET_EXCEEDED'); assert.equal(budget.report.stress.outcome, 'BUDGET_EXHAUSTED'); assert.equal(budget.report.stress.counterexamples, 0);
console.log('PASS distinct legal outputs accepted by selected testlib Checker; total budget exhaustion is separate from counterexamples.');
await writeFile('.local/verify-p3-stress.json', JSON.stringify({ problemId: p.id, multiAnswerRunId: multi.id, budgetRunId: budget.id, foundRunId: found.id, replayRunId: replay.id, canceledRunId: canceled.id, completedRunId: completed.id, testId: applied.id, inputHash: counter.inputHash, cancelElapsedMs, checks: ['counterexample', 'saved-input replay', 'apply revision', 'duplicate rejected', 'CAS', 'private download', 'stale rejected', 'cancel preserves evidence', 'next run succeeds', 'multi-answer Checker', 'budget exhausted'] }, null, 2));
console.log('PASS cancellation preserves counterexample and execution evidence; subsequent real run completes.'); process.exit(0);
