import assert from'node:assert/strict';import{readFile,writeFile}from'node:fs/promises';import{randomUUID,createHash}from'node:crypto';import{Client}from'./http-client.ts';import{readArchive,writeArchive,parseJson}from'@problemforge/problem-format';
const c=new Client(),admin=new Client(),f=JSON.parse(await readFile('.local/verify-p2-fixture.json','utf8'));await c.login(f.authorEmail,f.authorPassword);await admin.bootstrap();
const packages=JSON.parse(await readFile('.local/verify-p4-packages.json','utf8')),prior=JSON.parse(await readFile('.local/verify-p4-contest.json','utf8')),main=await c.call(`/contests/${prior.contestId}`),source=packages.nativeProblemId;
const p=await c.call(`/problems/${source}`),beamer=p.documents.find((d:any)=>d.kind==='EDITORIAL_BEAMER');await c.call(`/documents/${beamer.id}`,'PUT',{expectedVersion:beamer.version,enabled:false,body:beamer.currentRevision.body,metadata:beamer.currentRevision.metadata,templateVersionId:beamer.templateVersionId,sampleRevisionIds:[]});
const working=await c.call(`/problems/${source}/working-revision`);assert(working.acceptanceRunId,'仅停用文稿不改变已验证算法');const r=await c.call(`/problems/${source}/revisions`,'POST',{expectedHash:working.hash,label:'缺稿与显式子集边界'});if(r.state!=='APPROVED'){await c.call(`/revisions/${r.id}/review`,'POST',{action:'SUBMIT',message:''});await c.call(`/revisions/${r.id}/review`,'POST',{action:'APPROVE',message:''});}await c.call(`/revisions/${r.id}/review`,'POST',{action:'FREEZE',message:''});
const data={...main.data,title:'P4 缺稿与权限边界',items:[main.data.items[1],{problemId:source,revisionId:r.id,code:'D',lectureOrder:4}]};const contest=await c.call('/contests','POST',{expectedVersion:0,data});const frozen=await c.call(`/contests/${contest.id}/freeze`,'POST',{expectedVersion:contest.version});
const missing=await c.call(`/contests/${contest.id}/builds`,'POST',{revisionId:frozen.id,kinds:['EDITORIAL_DOCUMENT','EDITORIAL_BEAMER']},422);assert.equal(missing.code,'MISSING_MATERIAL');assert.deepEqual(missing.details,[{code:'D',kind:'EDITORIAL_BEAMER',problemId:source}]);assert.equal((await c.call(`/contests/${contest.id}/builds`)).length,0);
const subset=await c.call(`/contests/${contest.id}/builds`,'POST',{revisionId:frozen.id,kinds:['EDITORIAL_BEAMER'],subset:[main.data.items[1].problemId]});let built:any;for(let i=0;i<180;i++){built=await c.call(`/builds/${subset.builds[0].id}`);if(['FAILED','CANCELED','SUCCEEDED'].includes(built.state))break;await new Promise(r=>setTimeout(r,500));}assert.equal(built.state,'SUCCEEDED',built.log);assert.equal(built.input.explicitSubset,true);assert.deepEqual(built.input.contest.entries.map((e:any)=>e.code),['B']);
// A normal session is generated with the exact credential held only in this process.
const password=`P4-${randomUUID()}-Aa1`,viewer=await admin.call('/admin/users','POST',{email:`p4-viewer-${randomUUID()}@example.test`,name:'比赛查看者',password,role:'USER'}),v=new Client();await v.login(viewer.email,password);
await c.call(`/contests/${contest.id}/members`,'PUT',{targetType:'USER',targetId:viewer.id,role:'VIEWER',languages:[]});await v.call(`/contests/${contest.id}`);await v.call(`/problems/${source}`, 'GET',undefined,404);await v.call(`/contests/${contest.id}/builds`,'POST',{revisionId:frozen.id,kinds:['STATEMENT']},403);
const e=await c.call(`/contests/${contest.id}/exports`,'POST',{revisionId:frozen.id,purpose:'STATEMENT',format:'NATIVE'});await v.bytes(`/exports/${e.id}/file`);await c.call(`/contests/${contest.id}/members`,'DELETE',{targetType:'USER',targetId:viewer.id});await v.bytes(`/exports/${e.id}/file`,404);await v.call(`/builds/${built.id}`,'GET',undefined,404);
// Template-only edit carries review but does not manufacture another Judge run.
const doc=(await c.call(`/problems/${source}`)).documents.find((d:any)=>d.kind==='EDITORIAL_DOCUMENT'),template=(await c.call('/templates')).find((t:any)=>t.template.kind==='EDITORIAL_DOCUMENT'&&t.id!==doc.templateVersionId);
await c.call(`/documents/${doc.id}`,'PUT',{expectedVersion:doc.version,enabled:doc.enabled,body:doc.currentRevision.body,metadata:doc.currentRevision.metadata,templateVersionId:template.id,sampleRevisionIds:[]});const changed=await c.call(`/problems/${source}/working-revision`);assert.equal(changed.judgeHash,working.judgeHash);assert.equal(changed.acceptanceRunId,working.acceptanceRunId);const styleRevision=await c.call(`/problems/${source}/revisions`,'POST',{expectedHash:changed.hash,label:'纯模板绑定更新'});assert.equal(styleRevision.state,'APPROVED');assert((await c.call(`/revisions/${styleRevision.id}`)).decisions.some((d:any)=>d.action==='CARRY_APPROVAL'));
// Native transport keeps arbitrary bytes; copied approval and current acceptance are still absent.
const files=await readArchive(await readFile('.local/p4-packages/native.zip')),json=parseJson(files.get('problemforge.json')!),raw=Buffer.from([0,255,13,10,32]),hash=createHash('sha256').update(raw).digest('hex');files.set(`blobs/${hash}`,raw);json.manifest.tests.push({id:'rawcase',revisionId:'rawcase-r',version:1,number:9998,groupName:'raw',isSample:false,enabled:false,notes:'二进制传输验证',input:{key:`blobs/${hash}`,hash,bytes:raw.length},answer:null,provenance:null});json.manifest.documents[0].template={...json.manifest.documents[0].template,id:'missing-instance-template'};files.set('problemforge.json',Buffer.from(JSON.stringify(json)));
const inspected=await c.call('/imports/inspect','POST',{format:'NATIVE',base64:(await writeArchive(files)).toString('base64'),profileMap:{}});assert(inspected.canImport);assert(inspected.issues.some((i:any)=>i.area==='templates'&&i.status==='WARNING'));const rawProblem=await c.call(`/imports/${inspected.id}/commit`,'POST',{reportHash:inspected.reportHash,title:'原生二进制与缺失模板验证',acceptWarnings:true});const rs=await c.call(`/problems/${rawProblem.id}/working-revision`),rawCase=rs.manifest.tests.find((t:any)=>t.number===9998);assert.equal(rawCase.input.hash,hash);assert.deepEqual(await c.bytes(`/test-revisions/${rawCase.revisionId}/input`),raw);assert(rs.manifest.documents.some((d:any)=>!d.template));
await writeFile('.local/verify-p4-boundaries.json',JSON.stringify({contestId:contest.id,revisionId:frozen.id,subsetBuildId:built.id,styleRevisionId:styleRevision.id,rawProblemId:rawProblem.id,checks:['missing Beamer reports exact problem and creates no children','explicit subset uses real TeX with original B code','contest VIEWER cannot edit contest or access source','revoked membership denies saved package and PDF task','style change carries approval and same Judge dependency/run','NUL invalid UTF8 CRLF bytes remain exact','missing cross-instance template remains unbound']},null,2));console.log('PASS P4 missing-material, permissions, template-only review and binary import boundaries');process.exit(0);
