import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { Client } from './http-client.ts';
const fixture=JSON.parse(await readFile('.local/verify-p2-fixture.json','utf8'));
const c=new Client(),admin=new Client();await c.login(fixture.authorEmail,fixture.authorPassword);await admin.bootstrap();
const suffix=Date.now(),password=randomUUID()+'Aa!';
const reviewer=await admin.call('/admin/users','POST',{email:`p4-review-${suffix}@example.test`,name:'P4 审题人',password,role:'USER'});
const translator=await admin.call('/admin/users','POST',{email:`p4-translate-${suffix}@example.test`,name:'P4 英文翻译',password,role:'USER'});
const review=new Client(),translation=new Client();await review.login(reviewer.email,password);await translation.login(translator.email,password);
const source=JSON.parse(await readFile('.local/verify-p3-groups.json','utf8'));
const p=await c.call(`/problems/${source.problemId}/copy`,'POST',{title:`P4 协作与固定修订 · ${suffix}`});
await c.call(`/problems/${p.id}/languages`,'POST',{language:'en'});
await c.call(`/problems/${p.id}/members`,'PUT',{targetType:'USER',targetId:translator.id,role:'TRANSLATOR',languages:['en']});
const groupId=randomUUID();await admin.call(`/admin/groups/${groupId}`,'PUT',{name:`P4 审题组 ${suffix}`,userIds:[reviewer.id],expectedVersion:0});
await c.call(`/problems/${p.id}/members`,'PUT',{targetType:'GROUP',targetId:groupId,role:'REVIEWER',languages:[]});
const visible=await translation.call(`/problems/${p.id}`);assert(visible.documents.every((d:any)=>d.language==='en'));assert(!('judgeSettings'in visible));
const english=visible.documents.find((d:any)=>d.kind==='STATEMENT');
const saveDoc=(client:Client,d:any,body:string)=>client.call(`/documents/${d.id}`,'PUT',{expectedVersion:d.version,body,metadata:d.currentRevision.metadata,enabled:d.enabled,templateVersionId:d.templateVersionId,sampleRevisionIds:d.currentRevision.sampleRevisionIds});
await saveDoc(translation,english,'Add the two given integers.');await translation.call(`/problems/${p.id}/programs`,'GET',undefined,403);
const workspace=await c.call(`/problems/${p.id}`),zh=workspace.documents.find((d:any)=>d.kind==='STATEMENT'&&d.language==='zh-CN');
await translation.call(`/documents/${zh.id}/history`,'GET',undefined,404);
await translation.call(`/documents/${english.id}`,'PUT',{expectedVersion:english.version+1,body:'Changed',metadata:english.currentRevision.metadata,enabled:false,templateVersionId:null,sampleRevisionIds:[]},403);
const run=await c.waitRun((await c.call(`/problems/${p.id}/test-runs`,'POST',{purpose:'ACCEPTANCE',requestKey:randomUUID()})).id);assert.equal(run.state,'SUCCEEDED',run.log);assert.equal(run.accepted,true);
let working=await c.call(`/problems/${p.id}/working-revision`);assert.equal(working.acceptanceRunId,run.id);
let revision=await c.call(`/problems/${p.id}/revisions`,'POST',{expectedHash:working.hash,label:'三组计分与中英稿件'});
await c.call(`/revisions/${revision.id}/review`,'POST',{action:'SUBMIT',message:'提交固定清单'});
const comment=await review.call(`/revisions/${revision.id}/comments`,'POST',{body:'已核对 100 / 35 / 0 分和依赖阻断。',anchor:'groups'});
await review.call(`/review-comments/${comment.id}`,'PUT',{resolved:true});
await review.call(`/revisions/${revision.id}/review`,'POST',{action:'APPROVE',message:'同意本次修订'});
await c.call(`/revisions/${revision.id}/review`,'POST',{action:'FREEZE',message:'用于 P4 比赛固定版本'});
const oldHash=revision.hash;await saveDoc(c,zh,zh.currentRevision.body+'\n工作副本新增说明。');
const history=await c.call(`/problems/${p.id}/revisions`);assert.equal(history[0].reviewStale,true);assert.equal(history[0].state,'FROZEN');
assert.equal((await c.call(`/revisions/${revision.id}`)).hash,oldHash);assert((await c.call(`/revisions/${revision.id}/diff`)).some((d:any)=>d.path==='documents'));
await c.call(`/problems/${p.id}/revisions`,'POST',{expectedHash:working.hash,label:'冲突不得覆盖'},409);
working=await c.call(`/problems/${p.id}/working-revision`);
const restored=await c.call(`/revisions/${revision.id}/restore`,'POST',{expectedHash:working.hash,label:'回滚形成新的工作版本'});assert.equal(restored.number,2);assert.equal(restored.state,'DRAFT');
const back=await c.call(`/problems/${p.id}`);assert.equal(back.documents.find((d:any)=>d.id===zh.id).currentRevision.body,zh.currentRevision.body);assert(back.documents.find((d:any)=>d.id===zh.id).version>zh.version);
await admin.call(`/admin/groups/${groupId}`,'PUT',{name:`P4 审题组 ${suffix}`,userIds:[],expectedVersion:1});await review.call(`/revisions/${revision.id}`,'GET',undefined,404);
const after=await c.waitRun((await c.call(`/problems/${p.id}/test-runs`,'POST',{purpose:'ACCEPTANCE',requestKey:randomUUID()})).id);assert.equal(after.state,'SUCCEEDED',after.log);assert.equal(after.accepted,true);
await writeFile('.local/verify-p4-collaboration.json',JSON.stringify({problemId:p.id,frozenRevisionId:revision.id,restoredRevisionId:restored.id,runId:run.id,restoredRunId:after.id,reviewerId:reviewer.id,translatorId:translator.id,checks:['copy keeps source and raw data','group grant and revocation','translator only en content','program and other-language denial','real acceptance','version-bound comment approval freeze','working edits mark stale but preserve frozen snapshot','CAS conflict','rollback creates new versions','restored real acceptance']},null,2));
console.log('PASS P4 collaboration, current authorization, immutable revision/review/freeze, CAS, rollback and real Judge acceptance.');process.exit(0);
