import assert from'node:assert/strict';import{readFile,writeFile,readdir,mkdir}from'node:fs/promises';import{randomUUID}from'node:crypto';import{join}from'node:path';
import{readArchive,writeArchive,parseJson,readXml}from'@problemforge/problem-format';import{Client}from'./http-client.ts';
const c=new Client(),fixture=JSON.parse(await readFile('.local/verify-p2-fixture.json','utf8'));await c.login(fixture.authorEmail,fixture.authorPassword);const contest=JSON.parse(await readFile('.local/verify-p4-contest.json','utf8'));const source=contest.finalItems[0],current=contest.finalItems[2];await mkdir('.local/p4-packages',{recursive:true});
const full=await c.call(`/problems/${source.problemId}/exports`,'POST',{revisionId:source.revisionId,purpose:'FULL',format:'NATIVE'});const bytes=await c.bytes(`/exports/${full.id}/file`);await writeFile('.local/p4-packages/native.zip',bytes);const native=parseJson((await readArchive(bytes)).get('problemforge.json')!);
const inspected=await c.call('/imports/inspect','POST',{format:'NATIVE',base64:bytes.toString('base64'),profileMap:{}});assert(inspected.canImport,JSON.stringify(inspected.issues));const imported=await c.call(`/imports/${inspected.id}/commit`,'POST',{reportHash:inspected.reportHash,title:'原生往返 · 分组求和',acceptWarnings:true});const repeat=await c.call(`/imports/${inspected.id}/commit`,'POST',{reportHash:inspected.reportHash,title:'不应重复创建',acceptWarnings:true});assert.equal(repeat.id,imported.id);
const snap=await c.call(`/problems/${imported.id}/working-revision`);assert.deepEqual(snap.manifest.programs.map((p:any)=>p.source).sort(),native.manifest.programs.map((p:any)=>p.source).sort());assert.deepEqual(snap.manifest.tests.map((t:any)=>[t.number,t.input.hash,t.answer?.hash]),native.manifest.tests.map((t:any)=>[t.number,t.input.hash,t.answer?.hash]));assert.deepEqual(snap.manifest.documents.map((d:any)=>d.body).sort(),native.manifest.documents.map((d:any)=>d.body).sort());assert.equal(snap.manifest.groups.groups.length,native.manifest.groups.groups.length);assert.equal(snap.acceptanceRunId,null);assert((await c.call(`/problems/${imported.id}/revisions`)).every((r:any)=>r.state==='DRAFT'));
const run=await c.waitRun((await c.call(`/problems/${imported.id}/test-runs`,'POST',{purpose:'ACCEPTANCE',requestKey:randomUUID()})).id);assert.equal(run.state,'SUCCEEDED',run.log);assert.equal(run.accepted,true,JSON.stringify(run.report));console.log('Native roundtrip and real Linux acceptance passed');
const purposes=['STATEMENT','EDITORIAL_DOCUMENT','EDITORIAL_BEAMER','DATA','REFERENCE'];const exports=[];
for(const purpose of purposes){const e=await c.call(`/problems/${current.problemId}/exports`,'POST',{revisionId:current.revisionId,purpose,format:'NATIVE'});const archive=await readArchive(await c.bytes(`/exports/${e.id}/file`)),m=parseJson(archive.get('problemforge.json')!).manifest;
 if(purpose.startsWith('EDITORIAL')||purpose==='STATEMENT'){assert(m.documents.every((d:any)=>d.kind===purpose));assert.equal(m.programs.length,0);assert.equal(m.tests.length,0);assert.equal(m.selfTests.length,0);assert.equal(m.plans.length,0);}
 if(purpose==='REFERENCE'){assert.equal(m.tests.length,0);assert.equal(m.documents.length,0);assert(m.programs.every((p:any)=>['MAIN_SOLUTION','CORRECT_SOLUTION'].includes(p.role)));}
 if(purpose==='DATA'){assert.equal(m.documents.length,0);assert(m.tests.every((t:any)=>t.answer));assert(!m.programs.some((p:any)=>p.role.includes('SOLUTION')));}
 exports.push(e.id);
 if(purpose==='STATEMENT'){const release=await c.call(`/problems/${current.problemId}/releases`,'POST',{exportId:e.id});const anon=new Client();assert.deepEqual(await anon.bytes(`/released/${release.token}/file`),await c.bytes(`/exports/${e.id}/file`));await anon.bytes(`/exports/${full.id}/file`,401);await c.call(`/releases/${release.id}/revoke`,'POST');await anon.bytes(`/released/${release.token}/file`,404);}
}
const bundle=await c.call(`/contests/${contest.contestId}/exports`,'POST',{revisionId:contest.contestRevisionId,purpose:'STATEMENT',format:'NATIVE'});const bf=await readArchive(await c.bytes(`/exports/${bundle.id}/file`));assert.deepEqual([...bf.keys()].sort(),['contest.json','problems/A.zip','problems/B.zip','problems/C.zip']);
const files=new Map<string,Buffer>();async function collect(dir:string,prefix=''){for(const ent of await readdir(dir,{withFileTypes:true})){const name=prefix+ent.name;if(ent.isDirectory())await collect(join(dir,ent.name),name+'/');else files.set(name,await readFile(join(dir,ent.name)));}}await collect('fixtures/polygon/sum');const polygonZip=await writeArchive(files);await writeFile('.local/p4-packages/polygon-sample.zip',polygonZip);
const pi=await c.call('/imports/inspect','POST',{format:'POLYGON',base64:polygonZip.toString('base64'),profileMap:{}});assert(pi.canImport,JSON.stringify(pi.issues));assert(pi.issues.some((i:any)=>i.area.includes('external-style.sty')));const pp=await c.call(`/imports/${pi.id}/commit`,'POST',{reportHash:pi.reportHash,title:'Polygon 离线子集 · Sum',acceptWarnings:true});const ps=await c.call(`/problems/${pp.id}/working-revision`);assert.equal(ps.manifest.programs.length,4);assert.equal(ps.manifest.plans[0].seed,'5');assert.equal(ps.manifest.plans[0].enabled,false);assert.equal(ps.manifest.selfTests.length,2);assert.equal(ps.manifest.groups.groups[1].dependencies[0],'g20');assert(ps.manifest.documents.every((d:any)=>d.template===null));
const pr=await c.waitRun((await c.call(`/problems/${pp.id}/test-runs`,'POST',{purpose:'ACCEPTANCE',requestKey:randomUUID()})).id);assert.equal(pr.state,'SUCCEEDED',pr.log);assert.equal(pr.accepted,true,JSON.stringify(pr.report));const self=await c.waitRun((await c.call(`/problems/${pp.id}/test-runs`,'POST',{purpose:'SELF_TEST',requestKey:randomUUID()})).id);assert.equal(self.state,'SUCCEEDED',self.log);
const revisions=await c.call(`/problems/${pp.id}/revisions`);const pe=await c.call(`/problems/${pp.id}/exports`,'POST',{revisionId:revisions[0].id,purpose:'FULL',format:'POLYGON'});const polygonFiles=await readArchive(await c.bytes(`/exports/${pe.id}/file`));assert.equal(readXml(polygonFiles.get('problem.xml')!).name,'problem');assert(pe.report.some((i:any)=>i.status==='BLOCKED'));
// Unknown judging semantics are explicit blockers; malformed paths/XML are rejected before import.
files.set('problem.xml',Buffer.from(files.get('problem.xml')!.toString().replace('points-policy="complete-group"','points-policy="each-test"')));const unsupported=await c.call('/imports/inspect','POST',{format:'POLYGON',base64:(await writeArchive(files)).toString('base64'),profileMap:{}});assert.equal(unsupported.canImport,false);await c.call(`/imports/${unsupported.id}/commit`,'POST',{reportHash:unsupported.reportHash,title:'不可导入',acceptWarnings:true},409);
files.set('problem.xml',Buffer.from('<!DOCTYPE problem [<!ENTITY leak SYSTEM "file:///etc/passwd">]><problem>&leak;</problem>'));await c.call('/imports/inspect','POST',{format:'POLYGON',base64:(await writeArchive(files)).toString('base64'),profileMap:{}},422);
const safe=await writeArchive(new Map([['safe.txt',Buffer.from('x')]]));const unsafe=Buffer.from(safe.toString('latin1').replaceAll('safe.txt','../x.txt'),'latin1');await c.call('/imports/inspect','POST',{format:'POLYGON',base64:unsafe.toString('base64'),profileMap:{}},422);
await writeFile('.local/verify-p4-packages.json',JSON.stringify({nativeExportId:full.id,nativeProblemId:imported.id,nativeRunId:run.id,scopedExports:exports,bundleId:bundle.id,polygonProblemId:pp.id,polygonRunId:pr.id,polygonSelfTestRunId:self.id,polygonReceipt:pi.id,polygonExportId:pe.id,checks:['native source/body/bytes/groups roundtrip','import idempotence and no inherited approval or acceptance','real Linux native and Polygon acceptance','Polygon validator selftests','six purpose allowlists','contest per-problem package bundle','public statement package isolation and revoke','unknown scoring blocked','XML DTD rejected','ZIP traversal rejected'],sampleOrigin:'Self-authored explicit-subset fixture, not downloaded from Polygon; no external upload'},null,2));console.log('PASS P4 package roundtrip, purpose isolation, Polygon subset and hostile archive/XML refusals');process.exit(0);
