import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { db } from '@problemforge/database';
import { root, sha256 } from '@problemforge/domain';
import { Client } from './http-client.ts';
import { makeTestZip } from '../fixtures/judge/zip.ts';

// Explicit real HTTP / DB / Linux Judge integration; never part of test:quick.
const administrator = new Client(), author = new Client(), outsider = new Client();
await administrator.bootstrap();
const suffix = randomBytes(5).toString('hex'), password = randomBytes(24).toString('base64url');
const a = await administrator.call('/admin/users', 'POST', { email: `p2-author-${suffix}@problemforge.local`, name: 'P2 出题人', password, role: 'USER' });
const o = await administrator.call('/admin/users', 'POST', { email: `p2-outsider-${suffix}@problemforge.local`, name: 'P2 权限检查', password: password + 'o', role: 'USER' });
await author.login(a.email, password); await outsider.login(o.email, password + 'o');
await author.call('/admin/compile-profiles', 'POST', { name: '无权限配置', language: 'CPP17', enabled: true, config: { optimization: 'O2', warnings: true, compileTimeMs: 10000, compileMemoryMb: 512 } }, 403);
const profiles = await author.call('/compile-profiles');
const source = (file: string) => readFile(resolve(root, 'fixtures/judge', file), 'utf8');
const b64 = (input: string | Buffer) => Buffer.from(input).toString('base64');
const program = async (problemId: string, name: string, file: string, role: string, language = 'CPP17', enabled = true) => author.call(`/problems/${problemId}/programs`, 'POST', { name, role, source: await source(file), profileId: profiles.find((p: any) => p.language === language && p.enabled).id, expectedVerdicts: [role === 'WRONG_SOLUTION' ? 'WA' : role === 'TIME_LIMIT_SOLUTION' ? 'TLE' : 'AC'], notes: '', enabled });
const saveProgram = (p: any, code: string, enabled = p.enabled) => ({ name: p.name, role: p.role, profileId: p.profileId, source: code, expectedVerdicts: p.expectedVerdicts, notes: p.notes, enabled, expectedVersion: p.version });
const test = (problemId: string, number: number, input: string | Buffer, answer: string | Buffer | null = null, isSample = false, enabled = true) => author.call(`/problems/${problemId}/tests`, 'POST', { number, inputBase64: b64(input), answerBase64: answer === null ? null : b64(answer), groupName: 'main', isSample, enabled, notes: '' });
const selfTest = (problemId: string, name: string, kind: string, programId: string | null, expected: string, input: string, answer = '', output = '') => author.call(`/problems/${problemId}/self-tests`, 'POST', { name, kind, programId, expected, inputBase64: b64(input), answerBase64: b64(answer), outputBase64: b64(output), enabled: true });
const run = async (problemId: string, purpose: string) => {
  const task = await author.call(`/problems/${problemId}/test-runs`, 'POST', { purpose, requestKey: randomUUID() });
  return author.waitRun(task.id);
};
const succeeded = (r: any) => assert.equal(r.state, 'SUCCEEDED', `${r.purpose} ${r.errorCode}: ${r.log}`);
const sum = await author.call('/problems', 'POST', { title: `A + B · P2 验证 ${suffix}`, language: 'zh-CN' });
const main = await program(sum.id, '主标程 C++17', 'sum-main.cpp', 'MAIN_SOLUTION');
const correct = await program(sum.id, '正确解 Python', 'sum-correct.py', 'CORRECT_SOLUTION', 'PYTHON3');
let wrong = await program(sum.id, '正常退出的错误解', 'sum-wrong.py', 'WRONG_SOLUTION', 'PYTHON3');
const validator = await program(sum.id, '严格输入 Validator', 'sum-validator.cpp', 'VALIDATOR');
const generator = await program(sum.id, '有种子的生成器', 'sum-generator.py', 'GENERATOR', 'PYTHON3');
await author.call(`/programs/${wrong.id}`, 'PUT', { ...saveProgram(wrong, wrong.currentRevision.source), compileCommand: 'sh arbitrary' }, 400);
await test(sum.id, 1, '1 2\n', null, true); await test(sum.id, 2, '-5 4\n');
await author.call(`/problems/${sum.id}/generator-plans`, 'POST', { name: '小规模生成', programId: generator.id, argv: ['50'], seed: '7', count: 2, numberStart: 10, groupName: 'generated', isSample: false, enabled: true });
await selfTest(sum.id, '合法输入', 'VALIDATOR', validator.id, 'ACCEPT', '1 2\n');
await selfTest(sum.id, '越界输入', 'VALIDATOR', validator.id, 'REJECT', '2000 1\n');
await selfTest(sum.id, 'token 接受', 'CHECKER', null, 'AC', '1 2\n', '3\n', ' 3 \n');
await selfTest(sum.id, 'token 拒绝', 'CHECKER', null, 'WA', '1 2\n', '3\n', '0\n');
const submitKey = randomUUID(), request = { purpose: 'ACCEPTANCE', requestKey: submitKey };
const queued = await author.call(`/problems/${sum.id}/test-runs`, 'POST', request);
assert.equal((await author.call(`/problems/${sum.id}/test-runs`, 'POST', request)).id, queued.id, '重复提交必须返回同一任务');
const acceptance = await author.waitRun(queued.id); succeeded(acceptance); assert.equal(acceptance.accepted, true);
assert(acceptance.report.matrix.filter((c: any) => c.programId === correct.id).every((c: any) => c.verdict === 'AC'));
assert(acceptance.report.matrix.filter((c: any) => c.programId === wrong.id).some((c: any) => c.verdict === 'WA'));
assert(acceptance.invocations.filter((i: any) => i.programId === wrong.id && i.phase === 'SOLUTION').every((i: any) => i.exitStatus === 0));
assert.equal(acceptance.cases.filter((c: any) => c.origin.type === 'GENERATOR').length, 2);
console.log('PASS ordinary problem: real compile / generate / Validator / answers / self-tests / AC-WA matrix; exit 0 still WA.');
await outsider.call(`/test-runs/${acceptance.id}`, 'GET', undefined, 404);
await db.problemMember.create({ data: { problemId: sum.id, userId: o.id, role: 'VIEWER' } });
await outsider.call(`/test-runs/${acceptance.id}`);
await outsider.call(`/programs/${wrong.id}`, 'PUT', saveProgram(wrong, 'print(1)'), 403);
await db.problemMember.delete({ where: { problemId_userId: { problemId: sum.id, userId: o.id } } });
await outsider.call(`/test-runs/${acceptance.id}`, 'GET', undefined, 404);
await outsider.bytes(`/invocations/${acceptance.invocations[0].id}/stdout`, 404);
const validation = await run(sum.id, 'VALIDATE'); succeeded(validation);
const answers = await run(sum.id, 'ANSWERS'); succeeded(answers);
const problem = await author.call(`/problems/${sum.id}`), doc = problem.documents.find((d: any) => d.kind === 'STATEMENT');
await author.call(`/documents/${doc.id}`, 'PUT', { expectedVersion: doc.version, body: doc.currentRevision.body + '\n正文修改不影响程序验收。\n', enabled: doc.enabled, metadata: doc.currentRevision.metadata, templateVersionId: doc.templateVersionId });
assert.equal((await author.call(`/test-runs/${acceptance.id}`)).stale, false);
let configuration = await author.call(`/problems/${sum.id}/judge-settings`);
await author.call(`/problems/${sum.id}/judge-settings`, 'PUT', { expectedVersion: configuration.version, settings: { ...configuration.settings, checkerMode: 'EXACT' } });
assert.equal((await author.call(`/test-runs/${validation.id}`)).stale, false);
assert.equal((await author.call(`/test-runs/${answers.id}`)).stale, true);
// Restore token semantics for the independently saved self-test declarations.
configuration = await author.call(`/problems/${sum.id}/judge-settings`);
await author.call(`/problems/${sum.id}/judge-settings`, 'PUT', { expectedVersion: configuration.version, settings: { ...configuration.settings, checkerMode: 'TOKENS' } });
const updatedMain = await author.call(`/programs/${main.id}`, 'PUT', saveProgram(main, main.currentRevision.source + '\n// new source revision\n'));
await author.call(`/programs/${main.id}`, 'PUT', saveProgram(main, 'old version overwrite'), 409);
assert.equal((await author.call(`/test-runs/${validation.id}`)).stale, false);
assert.equal((await author.call(`/test-runs/${answers.id}`)).stale, true);
wrong = await author.call(`/programs/${wrong.id}`, 'PUT', saveProgram(wrong, 'invalid python syntax !\n'));
const ce = await run(sum.id, 'ACCEPTANCE'); succeeded(ce); assert.equal(ce.accepted, false);
assert(ce.report.expectations.find((e: any) => e.programId === wrong.id).diagnostic.includes('不能作为击败'));
wrong = await author.call(`/programs/${wrong.id}`, 'PUT', saveProgram(wrong, await source('sum-wrong.py')));
console.log('PASS object authorization/revocation, strict fields, version conflict, dependency-specific stale results, CE never counts as defeating a wrong solution.');
const split = await author.call('/problems', 'POST', { title: `分拆整数 · 多解 SPJ ${suffix}`, language: 'zh-CN' });
await program(split.id, '主标程', 'split-main.cpp', 'MAIN_SOLUTION');
const alternative = await program(split.id, '不同合法输出', 'split-correct.py', 'CORRECT_SOLUTION', 'PYTHON3');
await program(split.id, '错误分拆', 'split-wrong.py', 'WRONG_SOLUTION', 'PYTHON3');
await program(split.id, 'Validator', 'split-validator.cpp', 'VALIDATOR');
const checker = await program(split.id, 'testlib Checker C++20', 'split-checker.cpp', 'CHECKER', 'CPP20');
configuration = await author.call(`/problems/${split.id}/judge-settings`);
await author.call(`/problems/${split.id}/judge-settings`, 'PUT', { expectedVersion: configuration.version, settings: { ...configuration.settings, checkerMode: 'CUSTOM' } });
await test(split.id, 1, '5\n'); await test(split.id, 2, '9\n');
await selfTest(split.id, '接受另一组合法输出', 'CHECKER', checker.id, 'AC', '5\n', '5 0\n', '0 5\n');
await selfTest(split.id, '拒绝错误和', 'CHECKER', checker.id, 'WA', '5\n', '5 0\n', '5 5\n');
const spj = await run(split.id, 'ACCEPTANCE'); succeeded(spj); assert.equal(spj.accepted, true);
assert(spj.report.matrix.filter((c: any) => c.programId === alternative.id).every((c: any) => c.verdict === 'AC'));
const mainCell = spj.report.matrix.find((c: any) => c.programId !== alternative.id && c.verdict === 'AC');
const alternativeCell = spj.report.matrix.find((c: any) => c.programId === alternative.id);
assert.notDeepEqual(await author.bytes(`/invocations/${mainCell.invocationId}/stdout`), await author.bytes(`/invocations/${alternativeCell.invocationId}/stdout`));
const badChecker = await author.call(`/programs/${checker.id}`, 'PUT', saveProgram(checker, '#include <cstdlib>\nint main() { std::abort(); }\n'));
const toolFailure = await run(split.id, 'ACCEPTANCE'); assert.equal(toolFailure.state, 'FAILED'); assert.equal(toolFailure.errorCode, 'CHECKER_TOOL_ERROR');
assert(toolFailure.invocations.some((i: any) => i.verdict === 'TOOL_ERROR' && i.status === 'Signalled'));
await author.call(`/programs/${checker.id}`, 'PUT', saveProgram(badChecker, await source('split-checker.cpp')));
console.log('PASS real C++20 testlib SPJ accepts different valid outputs; Checker crash is a tool failure.');
const strict = await author.call('/problems', 'POST', { title: `严格行格式 / 字节与导入 ${suffix}`, language: 'zh-CN' });
const strictChecker = await program(strict.id, '严格行 Checker', 'strict-lines-checker.cpp', 'CHECKER', 'CPP17', false);
await selfTest(strict.id, '行末空白通过', 'CHECKER', strictChecker.id, 'AC', '', '1\n2\n', '1  \n2\t\n');
await selfTest(strict.id, '整数同一行拒绝', 'CHECKER', strictChecker.id, 'WA', '', '1\n2\n', '1 2\n');
const strictRun = await run(strict.id, 'SELF_TEST'); succeeded(strictRun); assert(strictRun.report.selfTests.every((t: any) => t.passed));
const raw = Buffer.from([0, 255, 13, 10, 32, 13, 10]);
const rawTest = await test(strict.id, 1, raw, Buffer.from('answer\r\n'), false, false);
assert.deepEqual(await author.bytes(`/test-revisions/${rawTest.currentRevision.id}/input`), raw);
assert.equal(rawTest.currentRevision.inputHash, sha256(raw));
const duplicate = await test(strict.id, 2, raw, null, false, false); assert.equal(duplicate.duplicates[0].id, rawTest.id);
const archive = makeTestZip([{ name: 'tests/003.in', bytes: Buffer.from('zip\r\n') }, { name: 'tests/003.ans', bytes: Buffer.from('answer\r\n') }]);
const imported = await author.call(`/problems/${strict.id}/tests/import-zip`, 'POST', { base64: b64(archive), groupName: 'imported' });
assert.deepEqual(await author.bytes(`/test-revisions/${imported[0].currentRevision.id}/input`), Buffer.from('zip\r\n'));
await author.call(`/problems/${strict.id}/tests/import-zip`, 'POST', { base64: b64(makeTestZip([{ name: '../004.in', bytes: Buffer.from('unsafe') }])), groupName: 'main' }, 422);
console.log('PASS strict line Checker accept/reject pair; raw bytes/CRLF, duplicate warning, safe ZIP import and traversal rejection.');
const sampleCase = answers.cases.find((c: any) => c.number === 1);
// This historical answer run became stale after the main source revision: collection must fail.
await author.call(`/test-runs/${answers.id}/apply-data`, 'POST', { caseIds: [sampleCase.id] }, 409);
await mkdir(resolve(root, '.local'), { recursive: true });
const fixture = { authorEmail: a.email, authorPassword: password, sumId: sum.id, splitId: split.id, strictId: strict.id };
await writeFile(resolve(root, '.local/verify-p2-fixture.json'), JSON.stringify(fixture, null, 2), { mode: 0o600 });
await writeFile(resolve(root, '.local/verify-p2.json'), JSON.stringify({ checkedAt: new Date().toISOString(), sumId: sum.id, splitId: split.id, strictId: strict.id, runs: { acceptance: acceptance.id, validation: validation.id, answers: answers.id, ce: ce.id, spj: spj.id, toolFailure: toolFailure.id, strict: strictRun.id }, checks: ['real ordinary problem pipeline and generator snapshots', 'idempotent submit', 'AC / normal-exit WA', 'permission revocation for task and stdout', 'strict profile fields and version conflict', 'dependency-specific stale detection', 'CE is not a defeat', 'multiple-valid-output C++20 testlib SPJ', 'Checker crash is TOOL_ERROR', 'strict lines accept/reject', 'raw bytes / hash / duplicates / ZIP / traversal', 'stale answer adoption rejected'] }, null, 2));
console.log('PASS P2 targeted real integration. Evidence .local/verify-p2.json; current source changes deliberately keep historical runs stale.');
await db.$disconnect();
