<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { NButton, NModal, NInput, NSelect, NFormItem, NCheckbox, NInputNumber, NTag, useMessage } from 'naive-ui';
import { api } from '../api';
const profiles = ref<any[]>([]), draft = ref<any>(), show = ref(false), busy = ref(false); const message = useMessage();
async function load() { try { profiles.value = await api('/compile-profiles'); } catch (e) { message.error((e as Error).message); } } onMounted(load);
function edit(p?: any) { draft.value = p ? JSON.parse(JSON.stringify(p)) : { name: '', language: 'CPP17', enabled: true, config: { optimization: 'O2', warnings: true, compileTimeMs: 10000, compileMemoryMb: 512 } }; show.value = true; }
async function save() {
  busy.value = true;
  try { const p = draft.value; await api(p.id ? `/admin/compile-profiles/${p.id}` : '/admin/compile-profiles', { method: p.id ? 'PUT' : 'POST', body: JSON.stringify({ name: p.name, language: p.language, enabled: p.enabled, config: p.config, ...(p.id ? { expectedVersion: p.version } : {}) }) }); show.value = false; await load(); message.success('编译 profile 已保存，相关历史验收将显示过期'); }
  catch (e) { message.error((e as Error).message); } finally { busy.value = false; }
}
</script>
<template><div class="page-heading"><div><h1>编译配置</h1><p>管理员维护固定语言和编译选项，版本变化会进入后续任务快照</p></div><NButton type="primary" @click="edit()">创建 profile</NButton></div><div class="panel"><table class="data-table"><thead><tr><th>名称 / 版本</th><th>语言与选项</th><th>编译资源</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="p in profiles" :key="p.id"><td>{{ p.name }} · v{{ p.version }}<small>{{ p.hash.slice(0, 12) }}</small></td><td>{{ p.language }} · {{ p.config.optimization }}{{ p.config.warnings ? ' · 启用警告' : '' }}</td><td>{{ p.config.compileTimeMs }} ms / {{ p.config.compileMemoryMb }} MiB</td><td><NTag :type="p.enabled ? 'success' : 'default'">{{ p.enabled ? '启用' : '停用' }}</NTag></td><td><NButton size="small" @click="edit(p)">编辑</NButton></td></tr></tbody></table></div><NModal v-model:show="show" preset="card" title="管理员编译 profile" style="width: min(550px, 95vw)"><template v-if="draft"><NFormItem label="名称"><NInput v-model:value="draft.name"/></NFormItem><NFormItem label="固定语言"><NSelect v-model:value="draft.language" :options="['CPP17', 'CPP20', 'PYTHON3'].map(v => ({ label: v, value: v }))"/></NFormItem><NFormItem label="优化级别"><NSelect v-model:value="draft.config.optimization" :options="['O0', 'O2'].map(v => ({ label: v, value: v }))"/></NFormItem><NFormItem label="编译 CPU 限制 / ms"><NInputNumber v-model:value="draft.config.compileTimeMs" :min="1000" :max="30000"/></NFormItem><NFormItem label="编译内存 / MiB"><NInputNumber v-model:value="draft.config.compileMemoryMb" :min="128" :max="1024"/></NFormItem><div class="toolbar-left"><NCheckbox v-model:checked="draft.enabled">启用</NCheckbox><NCheckbox v-model:checked="draft.config.warnings">编译警告</NCheckbox></div><NButton type="primary" :loading="busy" @click="save">保存版本</NButton></template></NModal></template>
