<script setup lang="ts">
import{ref,computed,onMounted,onBeforeUnmount}from'vue';import{useRoute,onBeforeRouteLeave}from'vue-router';
import{NButton,NInput,NInputNumber,NSelect,NTag,NAlert,NFormItem,NTabs,NTab,NCheckbox,NEmpty,useMessage,useDialog}from'naive-ui';
import{kindLabels,kinds,type DocumentKind,type ContestDataValue}from'@problemforge/contracts';
import{useTaskEvents}from'../task-events';
import{api}from'../api';import MemberPanel from'../components/MemberPanel.vue';import PackagePanel from'../components/PackagePanel.vue';import PdfPreview from'../components/PdfPreview.vue';
import EditorFeedback from '../components/EditorFeedback.vue';
import { snapshot, mergeSaved, downloadDraft } from '../draft-state';
import { rememberedChoice, useUnsavedGuard } from '../editor-navigation';
const route=useRoute(),message=useMessage(),dialog=useDialog(),contest=ref<any>(),data=ref<ContestDataValue>(),dirty=ref(false),busy=ref(false),tab=rememberedChoice('contest-tab','arrange',['arrange','materials','members','packages']),saveError=ref('');
const problems=ref<any[]>([]),templates=ref<any[]>([]),problemId=ref<string|null>(null),sourceRevisions=ref<any[]>([]),sourceRevisionId=ref<string|null>(null);
const revisionId=ref<string|null>(null),bundles=ref<any[]>([]),selectedBuild=ref<any>(),releases=ref<any[]>([]),buildTab=ref('preview'),subset=ref<string[]>([]),useSubset=ref(false),missing=ref<any[]>([]);
const writable=computed(()=>['OWNER','EDITOR'].includes(contest.value?.role));
const chosenFrozen=computed(()=>contest.value?.revisions.find((r:any)=>r.id===revisionId.value));
const selectedItems=computed(()=>contest.value?.completeness.items??[]);

function changed(){dirty.value=true;}
useUnsavedGuard(()=>dirty.value||busy.value);
async function act(fn:()=>Promise<void>){busy.value=true;try{await fn();}catch(e){message.error((e as Error).message);if((e as any).code==='MISSING_MATERIAL')missing.value=(e as any).details??[];}finally{busy.value=false;}}
async function results(){bundles.value=await api(`/contests/${route.params.id}/builds`);releases.value=await api(`/contests/${route.params.id}/releases`);if(selectedBuild.value)await inspect(selectedBuild.value.id);}
async function load(){contest.value=await api(`/contests/${route.params.id}`);data.value=JSON.parse(JSON.stringify(contest.value.data));dirty.value=false;if(!revisionId.value)revisionId.value=contest.value.revisions[0]?.id??null;await results();}
onMounted(()=>act(async()=>{await load();problems.value=await api('/problems');templates.value=await api('/templates');}));
useTaskEvents(()=>results().catch(e=>message.error(e.message)),{contestId:String(route.params.id)});
async function chooseProblem(){sourceRevisionId.value=null;sourceRevisions.value=[];if(problemId.value)await act(async()=>{sourceRevisions.value=(await api(`/problems/${problemId.value}/revisions`)).filter((r:any)=>r.state==='FROZEN');});}
function add(){if(!problemId.value||!sourceRevisionId.value||!data.value)return;data.value.items.push({problemId:problemId.value,revisionId:sourceRevisionId.value,code:String.fromCharCode(65+data.value.items.length),lectureOrder:data.value.items.length+1});changed();problemId.value=null;sourceRevisionId.value=null;sourceRevisions.value=[];}
function move(i:number,delta:number){const items=data.value!.items;[items[i],items[i+delta]]=[items[i+delta],items[i]];changed();}
async function save(){if(busy.value||!data.value)return;busy.value=true;saveError.value='';const submitted=snapshot(data.value);try{const saved=await api(`/contests/${route.params.id}`,{method:'PUT',body:JSON.stringify({expectedVersion:contest.value.version,data:submitted})});data.value=mergeSaved(data.value,submitted,saved.data);dirty.value=JSON.stringify(data.value)!==JSON.stringify(saved.data);Object.assign(contest.value,saved);const updated=await api(`/contests/${route.params.id}`);contest.value.completeness=updated.completeness;contest.value.revisions=updated.revisions;message.success(dirty.value?'已保存提交时的编排；继续输入的修改仍未保存':'编排已保存；既有冻结清单保留');}catch(e){saveError.value=(e as Error).message;message.error(saveError.value);}finally{busy.value=false;}}
async function freeze(){if(dirty.value||busy.value)return;await act(async()=>{const r=await api(`/contests/${route.params.id}/freeze`,{method:'POST',body:JSON.stringify({expectedVersion:contest.value.version})});revisionId.value=r.id;const updated=await api(`/contests/${route.params.id}`);contest.value.revisions=updated.revisions;contest.value.completeness=updated.completeness;tab.value='materials';message.success(`已冻结比赛版本 #${r.number}`);});}
async function build(selectedKinds:DocumentKind[]){missing.value=[];await act(async()=>{const r=await api(`/contests/${route.params.id}/builds`,{method:'POST',body:JSON.stringify({revisionId:revisionId.value,kinds:selectedKinds,...(useSubset.value?{subset:subset.value}:{})})});await results();await inspect(r.builds[0].id);buildTab.value='log';});}
async function inspect(id:string){const b=await api(`/builds/${id}`);const row=bundles.value.flatMap(b=>b.builds).find(b=>b.id===id);selectedBuild.value={...b,stale:row?.stale??false};}
async function taskAction(action:'cancel'|'retry'){await act(async()=>{const r=await api(`/builds/${selectedBuild.value.id}/${action}`,{method:'POST'});await results();if(action==='retry')await inspect(r.id);});}
function publish(){dialog.warning({title:`公开发布${kindLabels[selectedBuild.value.kind as DocumentKind]}`,content:'只发布选中的 PDF。若为显式子集，文件仅包含选中的题目；其他资料保留各自的发布状态。',positiveText:'发布此 PDF',negativeText:'返回',onPositiveClick:()=>act(async()=>{await api(`/contests/${route.params.id}/releases`,{method:'POST',body:JSON.stringify({buildId:selectedBuild.value.id})});await results();})});}
async function revoke(id:string){await act(async()=>{await api(`/releases/${id}/revoke`,{method:'POST'});await results();});}
function templateOptions(kind:DocumentKind){return templates.value.filter(t=>t.template.kind===kind&&t.contestCapable&&t.languages.includes(data.value!.language)).map(t=>({label:`${t.template.name} · v${t.number}`,value:t.id}));}
function itemTitle(item:{problemId:string}){return problems.value.find(p=>p.id===item.problemId)?.title??selectedItems.value.find((p:any)=>p.problemId===item.problemId)?.title??item.problemId;}
</script>
<template><template v-if="contest&&data"><EditorFeedback :dirty="dirty" :saving="busy" :error="saveError" :version="contest.version" label="比赛编排" @export="downloadDraft(`contest-${contest.id}`,{id:contest.id,baseVersion:contest.version,data})"/><div class="workspace-heading"><div><div class="breadcrumb"><RouterLink to="/contests">比赛</RouterLink> / 工作区</div><h1>{{contest.title}}</h1></div><NTag>{{contest.role}} · 编排 v{{contest.version}}{{dirty?' · 未保存':''}}</NTag></div><div class="panel p4-panel"><NTabs v-model:value="tab"><NTab name="arrange">比赛编排</NTab><NTab name="materials">冻结与资料</NTab><NTab name="packages">题包与发布</NTab><NTab name="members">成员与权限</NTab></NTabs>
<div v-if="tab==='arrange'"><div class="p4-form-row"><NFormItem label="比赛名称"><NInput v-model:value="data.title" :disabled="!writable" @update:value="changed"/></NFormItem><NFormItem label="署名"><NInput v-model:value="data.author" :disabled="!writable" @update:value="changed"/></NFormItem><NFormItem label="语言"><NInput v-model:value="data.language" :disabled="!writable" @update:value="changed"/></NFormItem></div><div class="p4-form-row"><NFormItem label="场次"><NInput v-model:value="data.stage" :disabled="!writable" @update:value="changed"/></NFormItem><NFormItem label="页眉日期"><NInput v-model:value="data.dateHeader" :disabled="!writable" @update:value="changed"/></NFormItem><NFormItem label="封面日期"><NInput v-model:value="data.dateCover" :disabled="!writable" @update:value="changed"/></NFormItem></div><div class="p4-form-row"><NFormItem v-for="k in kinds" :key="k" :label="`${kindLabels[k]}模板（固定版本）`"><NSelect v-model:value="data.templates[k]" :options="templateOptions(k)" clearable :disabled="!writable" @update:value="changed"/></NFormItem></div>
<div v-if="writable" class="p4-toolbar"><NSelect v-model:value="problemId" :options="problems.filter(p=>!data!.items.some(i=>i.problemId===p.id)).map(p=>({label:p.title,value:p.id}))" filterable placeholder="选择有权访问的源题" @update:value="chooseProblem"/><NSelect v-model:value="sourceRevisionId" :options="sourceRevisions.map(r=>({label:`#${r.number} ${r.label}`,value:r.id}))" placeholder="已审核冻结的修订"/><NButton :disabled="!sourceRevisionId" @click="add">加入比赛</NButton></div><table class="data-table"><thead><tr><th>题号</th><th>题目 / 固定修订</th><th>Beamer 讲解顺序</th><th>题册顺序</th></tr></thead><tbody><tr v-for="(item,i) in data.items" :key="item.problemId"><td><NInput v-model:value="item.code" :disabled="!writable" style="width:85px" @update:value="changed"/></td><td>{{itemTitle(item)}}<small>{{item.revisionId}}</small></td><td><NInputNumber v-model:value="item.lectureOrder" :min="1" :max="100" :disabled="!writable" @update:value="changed"/></td><td><div class="p4-order-controls"><NButton :disabled="!writable||i===0" size="small" @click="move(i,-1)">上移</NButton><NButton :disabled="!writable||i===data.items.length-1" size="small" @click="move(i,1)">下移</NButton><NButton v-if="writable" size="small" @click="data.items.splice(i,1);changed()">移出</NButton></div></td></tr></tbody></table><div class="p4-toolbar"><NButton type="primary" :loading="busy" :disabled="!writable||!dirty" @click="save">保存编排</NButton><NButton :disabled="contest.role!=='OWNER'||dirty||!data.items.length" @click="freeze">检查完整性并冻结</NButton><span class="muted">冻结题面是必需项；两种题解可按需要分别构建。</span></div><h3>已保存清单的完整性</h3><table class="data-table"><thead><tr><th>题号与题目</th><th v-for="k in kinds" :key="k">{{kindLabels[k]}}</th></tr></thead><tbody><tr v-for="r in selectedItems" :key="r.problemId"><td>{{r.code}} · {{r.title}}</td><td v-for="k in kinds" :key="k"><NTag :type="r.materials[k]?'success':'warning'">{{r.materials[k]?'已提供':'缺稿或停用'}}</NTag></td></tr></tbody></table></div>
<template v-else-if="tab==='materials'"><div class="p4-toolbar"><NSelect v-model:value="revisionId" :options="contest.revisions.map((r:any)=>({label:`冻结 #${r.number}${r.current?' · 当前选定清单':' · 历史清单'}`,value:r.id}))" placeholder="先保存并冻结比赛"/><NButton @click="act(results)">刷新任务</NButton><NCheckbox v-model:checked="useSubset">显式选择题目子集</NCheckbox><NSelect v-if="useSubset" v-model:value="subset" multiple :options="selectedItems.map((i:any)=>({label:i.code+' · '+i.title,value:i.problemId}))" placeholder="选择完整稿件的题目"/></div><NAlert v-if="chosenFrozen&&!chosenFrozen.current" type="warning">当前选择的是历史冻结版本。可以检查历史内容，正式发布需要与当前比赛编排一致。</NAlert><div class="p4-toolbar"><NButton v-for="k in kinds" :key="k" :disabled="!revisionId||!writable||busy" @click="build([k])">生成{{kindLabels[k]}}{{k==='STATEMENT'?'题册':''}}</NButton><NButton type="primary" :disabled="!revisionId||!writable||busy" @click="build(['EDITORIAL_DOCUMENT','EDITORIAL_BEAMER'])">同时生成两种题解</NButton></div><NAlert v-if="missing.length" type="warning">缺少稿件：{{missing.map(m=>`${m.code} ${kindLabels[m.kind as DocumentKind]}`).join('；')}}。补齐或显式选取完整子集。</NAlert>
<div class="p4-build-grid"><aside class="p4-build-list"><template v-for="bundle in bundles" :key="bundle.id"><NTag :type="bundle.state==='PARTIAL_FAILED'?'warning':bundle.state==='SUCCEEDED'?'success':'default'">组合任务 · {{bundle.state}}</NTag><NButton v-for="b in bundle.builds" :key="b.id" :type="selectedBuild?.id===b.id?'primary':'default'" @click="inspect(b.id)">{{kindLabels[b.kind as DocumentKind]}} · {{b.state}}<br/>冻结 #{{b.input.contentVersion}} {{b.input.explicitSubset?' · 显式子集':''}} {{b.stale?' · 历史':''}}</NButton></template><NEmpty v-if="!bundles.length" description="尚无构建"/></aside><section v-if="selectedBuild"><div class="p4-toolbar"><NTag>{{selectedBuild.state}}</NTag><span class="muted">{{selectedBuild.id}}</span><NButton v-if="writable&&['QUEUED','RUNNING'].includes(selectedBuild.state)" @click="taskAction('cancel')">取消</NButton><NButton v-if="writable&&['FAILED','CANCELED'].includes(selectedBuild.state)" @click="taskAction('retry')">重试此子任务</NButton><NButton v-if="contest.role==='OWNER'" :disabled="selectedBuild.state!=='SUCCEEDED'||selectedBuild.stale||dirty" @click="publish">公开发布此 PDF</NButton></div><NTabs v-model:value="buildTab"><NTab name="preview">PDF 预览</NTab><NTab name="log">真实编译日志</NTab><NTab name="sources">固定来源</NTab></NTabs><PdfPreview v-if="buildTab==='preview'" :artifact-id="selectedBuild.artifacts[0]?.id"/><template v-else-if="buildTab==='log'"><NAlert v-if="selectedBuild.errorCode" type="error">{{selectedBuild.errorCode}}</NAlert><pre class="build-log">{{selectedBuild.log||'等待后台执行'}}</pre></template><div v-else><p>比赛冻结 {{selectedBuild.contestRevisionId}}<br/>模板 v{{selectedBuild.input.templateNumber}} · {{selectedBuild.input.templateHash}}</p><p v-for="e in selectedBuild.input.contest?.entries" :key="e.namespace">{{e.code}} · {{e.metadata.title}} · {{e.namespace}}</p><NAlert v-if="selectedBuild.input.explicitSubset" type="warning">此 PDF 仅包含以上显式选定的题目。</NAlert></div></section></div><h3>各类资料独立发布</h3><div v-for="r in releases" :key="r.id" class="publication-row"><NTag>{{kindLabels[r.purpose as DocumentKind]??r.purpose}}</NTag><span>{{r.revokedAt?'已撤回':'已发布'}}</span><a v-if="!r.revokedAt" :href="`/api/released/${r.token}/file`" target="_blank">下载该材料</a><NButton v-if="!r.revokedAt&&contest.role==='OWNER'" size="small" @click="revoke(r.id)">撤回</NButton></div></template>
<PackagePanel v-else-if="tab==='packages'" scope="contests" :id="contest.id" :owner="contest.role==='OWNER'"/><MemberPanel v-else scope="contests" :id="contest.id" :owner="contest.role==='OWNER'"/></div></template></template>
