<script setup lang="ts">
import { NAlert } from 'naive-ui';
</script>
<template><div class="page-heading"><div><h1>团队使用指引</h1><p>从私有草稿到审核冻结，再到整场出版；每个步骤都保留自己的版本和结果。</p></div><RouterLink :to="{path:'/problems',query:{q:'分组'}}">查找现有分组示例</RouterLink></div>
<NAlert type="info" class="spaced">保存失败或冲突时，本地输入仍保留。先点击「下载本地草稿」，再重新加载服务端版本对照合并。切换题面、文档题解、Beamer 或语言不会删除另一份稿件。刷新前请保存或导出未保存内容。</NAlert>
<div class="guide-grid"><section class="panel"><h2>出题人</h2><ol><li>在题目页创建或导入私有题目，填好名称、标签和负责人。</li><li>在「题面与双题解出版」选择语言、稿件及管理员发布的模板。三种稿件分别保存，停用格式仍保留正文。</li><li>在「程序、数据与验收」保存主标程、校验器及其他程序，准备测试、生成计划和分组；先保存配置再运行对应任务。</li><li>检查验收矩阵、失败日志与预期判定。修改程序或数据后旧结果可能过期，应重新验收。</li><li>保存当前工作副本为修订，提交审核。通过后由负责人冻结，供比赛选用。</li></ol></section>
<section class="panel"><h2>审题人</h2><ol><li>进入「组织、修订与协作 → 修订与审核」，明确选择本次审阅的修订。</li><li>查看差异、题面、题解、固定程序和验收报告，在该修订上留下评论。</li><li>检查预期错误解、边界数据、判题语义及题解一致性，再批准或要求修改。</li><li>内容或判题依赖改变后，旧批准可能过期。以当前修订提示为准，不能沿用旧成功任务冒充本次验收。</li></ol></section>
<section class="panel"><h2>管理员</h2><ol><li>在用户管理创建团队账号，题目和比赛成员权限分别设置；使用用户组分配重复职责。</li><li>模板中心复制新草稿、保存、验证真实 PDF，预览后发布。已发布版本不可原地编辑。</li><li>在账户设置管理密码与登录会话；用户遗失密码时发起一次性重置，安全转交链接。</li><li>在运行与审计检查依赖、任务和容量。升级前做一致备份，保留对应版本与恢复说明。</li></ol></section></div>
<section class="panel guide-extra"><h2>比赛资料与导出</h2><p>比赛编排选择已冻结的题目修订，确认题号、题册顺序及 Beamer 讲解顺序，保存并冻结比赛。题册、书面题解集和 Beamer 分别构建；缺稿时补齐或明确选择子集。检查真实 PDF 后，再按所需材料单独发布或导出。一个材料公开不会让其他材料自动公开。</p><p>原生 FULL 包适合完整源码交接；按用途选择题面、两种题解或数据等材料可以减少不必要的暴露。导入先读兼容报告，再确认创建私有草稿；新题需重新验收和审核。</p></section>
<section class="panel guide-extra"><h2>找到历史，继续编辑</h2><p>任务中心可按状态、用途、题目或比赛、时间筛选并翻到更早任务；地址保留当前页和选中的报告。实时提示不替换当前选择。已有 PDF 与日志可直接查看，无需重新执行任务。</p><p>当前浏览器标签页会记住各题的语言、稿件、功能区和程序选择。返回题目列表保留之前的搜索条件；「继续上次题目」回到最近工作区。只记导航位置，不把题面、源码、密码或凭据写入浏览器持久存储。</p><p>保存过程中继续输入的修改会保留为未保存状态。登录失效时先导出草稿再重新登录；下载的 JSON 包含私有正文或源码，请自行保管，恢复时逐项对照粘贴。</p></section></template>
<style scoped>.guide-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.guide-grid section,.guide-extra{padding:22px}.guide-grid h2,.guide-extra h2{font-size:18px;margin:0 0 14px}.guide-grid ol{padding-left:20px;margin:0}.guide-grid li{line-height:1.85;margin-bottom:12px}.guide-extra{margin-top:18px}.guide-extra p{font-size:14px;color:#586983}@media(max-width:1050px){.guide-grid{grid-template-columns:1fr}}</style>
