<script setup lang="ts">
import{ref,onMounted}from'vue';import{useRouter}from'vue-router';import{NSelect,NButton,NInput,NAlert,NCheckbox,NTag,useMessage}from'naive-ui';import{api,bytesBase64}from'../api';
const router=useRouter(),message=useMessage(),format=ref('NATIVE'),file=ref<File>(),receipt=ref<any>(),title=ref(''),accepted=ref(false),busy=ref(false),profileMap=ref('{}');
const history=ref<any[]>([]);onMounted(()=>api('/imports').then(rows=>history.value=rows).catch(e=>message.error(e.message)));
function openReceipt(r:any){receipt.value=r;title.value=r.title;accepted.value=false;}
function choose(e:Event){file.value=(e.target as HTMLInputElement).files?.[0];receipt.value=null;accepted.value=false;}
async function inspect(){if(!file.value)return;busy.value=true;try{if(file.value.size>24_000_000)throw new Error('ZIP 不能超过 24MB');receipt.value=await api('/imports/inspect',{method:'POST',body:JSON.stringify({format:format.value,base64:bytesBase64(new Uint8Array(await file.value.arrayBuffer())),profileMap:JSON.parse(profileMap.value)})});title.value=receipt.value.title;accepted.value=false;}catch(e){message.error((e as Error).message);}finally{busy.value=false;}}
async function commit(){busy.value=true;try{const p=await api(`/imports/${receipt.value.id}/commit`,{method:'POST',body:JSON.stringify({title:title.value,reportHash:receipt.value.reportHash,acceptWarnings:true})});await router.push(`/problems/${p.id}`);}catch(e){message.error((e as Error).message);}finally{busy.value=false;}}
</script>
<template><div class="page-heading"><div><h1>离线导入题目</h1><p>先检查文件与兼容报告，再创建我的私有工作副本</p></div><RouterLink to="/problems">返回题目列表</RouterLink></div><div class="panel p4-editor"><NAlert type="info">原生格式仅接受完整 v1 题包。比赛总包请先取出单题 ZIP。外部脚本、样式和无法转换的内容会保留在隔离原包中；模板由当地管理员维护。</NAlert><div class="p4-toolbar"><NSelect v-model:value="format" :options="[{label:'ProblemForge 原生 v1',value:'NATIVE'},{label:'Polygon problem.xml 离线包',value:'POLYGON'}]"/><input type="file" accept=".zip,application/zip" aria-label="选择离线题包" @change="choose"/><NButton type="primary" :loading="busy" :disabled="!file" @click="inspect">检查兼容性</NButton></div><details><summary>跨实例编译 profile 匹配（需要时）</summary><p>提供原 profile ID 到本地 profile ID 的 JSON 映射。重新检查会明确记录变更。</p><NInput v-model:value="profileMap" type="textarea" placeholder='{"原ID":"本地ID"}'/></details><details v-if="history.length"><summary>我的历史检查（刷新后可继续）</summary><div class="p4-list"><NButton v-for="r in history" :key="r.id" @click="openReceipt(r)">{{r.title}} · {{new Date(r.createdAt).toLocaleString('zh-CN')}} · {{r.format}} · {{r.committedProblemId?'已导入':'待处理'}}</NButton></div></details><template v-if="receipt"><h3>兼容报告 · {{receipt.counts.documents}} 份文稿 / {{receipt.counts.programs}} 个程序 / {{receipt.counts.tests}} 组数据</h3><div v-for="(r,i) in receipt.issues" :key="i" class="p4-comment"><NTag :type="r.status==='BLOCKED'?'error':r.status==='WARNING'?'warning':'success'">{{r.status==='BLOCKED'?'阻塞':r.status==='WARNING'?'需核对':'已映射'}}</NTag> {{r.area}}<p>{{r.message}}</p></div><a :href="`/api/exports/${receipt.id}/file`">下载隔离原包进行人工处理</a><NAlert v-if="!receipt.canImport" type="error">请修正阻塞项后重新上传检查；当前包不会创建可用题目。</NAlert><RouterLink v-else-if="receipt.committedProblemId" :to="`/problems/${receipt.committedProblemId}`">打开已导入的题目</RouterLink><template v-else><NInput v-model:value="title" placeholder="导入后的题目名称"/><NCheckbox v-model:checked="accepted">已核对上述报告；导入后重新绑定缺失模板、验收并冻结</NCheckbox><div class="p4-toolbar"><NButton type="primary" :disabled="!accepted||!title.trim()" :loading="busy" @click="commit">创建私有题目</NButton></div></template></template></div></template>
