<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { NButton, NTag, NAlert, NInput, useMessage } from 'naive-ui';
import { api } from '../api';
const health=ref<any>(),rows=ref<any[]>([]),cursor=ref<string|null>(null),action=ref(''),busy=ref(false),message=useMessage();
async function load(more=false){busy.value=true;try{if(!more)health.value=await api('/admin/operations');const q=new URLSearchParams();if(action.value)q.set('action',action.value);if(more&&cursor.value)q.set('cursor',cursor.value);const r=await api(`/admin/audit?${q}`);rows.value=more?[...rows.value,...r.rows]:r.rows;cursor.value=r.nextCursor;}catch(e){message.error((e as Error).message);}finally{busy.value=false;}}
onMounted(()=>load());
</script>
<template><div class="page-heading"><div><h1>运行与审计</h1><p>查看服务状态、存储配额及操作记录</p></div><NButton :loading="busy" @click="load()">刷新</NButton></div><section v-if="health" class="panel p4-editor"><NAlert :type="health.status==='ok'?'success':'warning'">{{health.status==='ok'?'各服务可用':'部分服务不可用，请查看下列状态'}}</NAlert><p>运行版本：{{health.version.buildId}} · {{health.version.mode}}<br/>Git {{health.version.gitCommit || "开发工作区，未标记发布版本"}}<br/>构建时间 {{health.version.builtAt || "—"}} · 数据库 {{health.version.migrations.length}} 个迁移 · {{health.version.migrationsMatch===true?"与镜像一致":health.version.migrationsMatch===false?"与镜像不一致，请检查升级状态":"开发环境"}}</p><details><summary>迁移版本</summary><p v-for="m in health.version.migrations" :key="m.name">{{m.name}} <small>{{m.checksum}}</small></p></details><div class="p4-toolbar"><NTag v-for="(state,name) in health.checks" :key="name" :type="state==='ok'?'success':'error'">{{name}} · {{state}}</NTag></div><p>私有存储 {{(health.storage.bytes/1048576).toFixed(1)}} / {{(health.storage.limit/1048576).toFixed(0)}} MiB · {{health.storage.objects}} 个文件 · {{health.storage.pending}} 个未完成写入预留</p><NAlert v-if="health.storage.status!=='ok'" type="warning">私有存储已使用 {{health.storage.percent.toFixed(1)}}%，告警线 {{health.storage.warningPercent}}%。请安排扩容或离线盘点；不会自动删除历史。</NAlert><p>未完成预留 {{(health.storage.pendingBytes/1048576).toFixed(2)}} MiB，最早 {{health.storage.oldestPendingAt?new Date(health.storage.oldestPendingAt).toLocaleString():'—'}}；编译缓存引用 {{health.storage.cache.objects}} 个登记文件 / {{(health.storage.cache.bytes/1048576).toFixed(2)}} MiB（包含在总用量内）。</p><details><summary>最近 30 天新增登记用量（UTC，包含预留）</summary><table class="data-table"><thead><tr><th>日期</th><th>新增文件</th><th>MiB</th></tr></thead><tbody><tr v-for="g in health.storage.growth" :key="g.day"><td>{{g.day}}</td><td>{{g.objects}}</td><td>{{(g.bytes/1048576).toFixed(2)}}</td></tr></tbody></table></details><p class="muted">一致性盘点和清理预览由管理员在停止写入后执行；所有冻结、发布和历史任务的文件引用均保留。备份执行结果保存在部署主机的维护记录中。</p><p>排队或执行：TeX {{health.tasks.builds}} · Judge {{health.tasks.judge}}。每人上限 {{health.quotas.buildsPerUser}} / {{health.quotas.judgePerUser}}；同一快照最多 {{health.quotas.attempts}} 次尝试。</p></section><section class="panel p4-editor"><div class="p4-toolbar"><NInput v-model:value="action" placeholder="按操作名筛选（留空查看全部）"/><NButton @click="load()">查询审计</NButton></div><table class="data-table"><thead><tr><th>时间 / 操作</th><th>操作者 / 对象</th><th>详情</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{new Date(r.createdAt).toLocaleString('zh-CN')}}<small>{{r.action}}</small></td><td>{{r.actorId||'系统'}}<small>{{r.resourceId||'—'}}</small></td><td><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{r.detail?JSON.stringify(r.detail):'—'}}</pre></td></tr></tbody></table><NButton v-if="cursor" :loading="busy" @click="load(true)">更早记录</NButton></section></template>
