<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { NButton, NInput, NModal, NFormItem, NTag, NEmpty, NCheckbox, useMessage } from 'naive-ui';
import { api } from '../api';
const problems = ref<any[]>([]); const filter = ref(''); const show = ref(false); const title = ref(''); const creating = ref(false); const message = useMessage(); const router = useRouter();
const users=ref<any[]>([]), archived=ref(false);
const person=(id:string)=>users.value.find(u=>u.id===id)?.name||'未指定';
const visible=computed(()=>problems.value.filter(p=>(archived.value||!p.archived)&&[p.title,...(p.tags||[]),person(p.responsibleId)].join(' ').toLowerCase().includes(filter.value.trim().toLowerCase())));
async function load() { try { const [p,d]=await Promise.all([api('/problems'),api('/directory')]); problems.value=p;users.value=d.users; } catch (e) { message.error((e as Error).message); } }
onMounted(load);
async function create() { creating.value = true; try { const result = await api('/problems', { method: 'POST', body: JSON.stringify({ title: title.value, language: 'zh-CN' }) }); router.push(`/problems/${result.id}`); } catch (e) { message.error((e as Error).message); } finally { creating.value = false; } }
</script>
<template><div class="page-heading"><div><h1>题目</h1><p>管理私有题目与出版资料</p></div><RouterLink to="/import">导入题包</RouterLink><NButton type="primary" @click="show = true">＋ 创建题目</NButton></div><div class="panel"><div class="panel-toolbar"><NInput v-model:value="filter" placeholder="搜索名称、标签或负责人" style="max-width: 360px" clearable /><NCheckbox v-model:checked="archived">包含已归档</NCheckbox><span class="muted">{{ visible.length }} 道题目</span></div><table class="data-table" v-if="visible.length"><thead><tr><th>题目名称</th><th>标签 / 负责人</th><th>文稿</th><th>最近更新</th><th></th></tr></thead><tbody><tr v-for="p in visible" :key="p.id"><td><RouterLink :to="`/problems/${p.id}`" class="problem-title">{{ p.title }}</RouterLink> <NTag v-if="p.archived" size="small">已归档</NTag><small>{{ p.id }}</small></td><td><NTag v-for="tag in p.tags" :key="tag" size="small">{{ tag }}</NTag><small>{{ person(p.responsibleId) }}</small></td><td>{{ p._count.documents }} 份独立文稿</td><td>{{ new Date(p.updatedAt).toLocaleString('zh-CN') }}</td><td><NButton size="small" @click="router.push(`/problems/${p.id}`)">打开工作区</NButton></td></tr></tbody></table><NEmpty v-else description="没有匹配的题目" class="empty" /></div><NModal v-model:show="show" preset="card" title="创建私有题目" style="width: 460px"><NFormItem label="题目名称"><NInput v-model:value="title" placeholder="例如：A + B" :maxlength="160" @keydown.enter="create" /></NFormItem><p class="muted">将分别创建简体中文题面、文档题解和 Beamer 题解。</p><NButton type="primary" :disabled="!title.trim()" :loading="creating" @click="create">创建并编辑</NButton></NModal></template>
