<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue';
import { NButton, NTag, NModal, NAlert, NEmpty, NTabs, NTab, useMessage } from 'naive-ui';
import { judgePurposeLabels, type JudgePurpose } from '@problemforge/contracts';
import { api, type Build } from '../api';
import PdfPreview from '../components/PdfPreview.vue';
import JudgeReport from '../components/JudgeReport.vue';
const builds = ref<Build[]>([]), runs = ref<any[]>([]), selected = ref<Build>(), selectedRun = ref<any>();
const tab = ref('judge'), show = ref(false), showRun = ref(false); const message = useMessage(); let timer: ReturnType<typeof setInterval>;
async function load() { try { [builds.value, runs.value] = await Promise.all([api('/builds'), api('/test-runs')]); if (selected.value) selected.value = await api(`/builds/${selected.value.id}`); if (selectedRun.value) selectedRun.value = await api(`/test-runs/${selectedRun.value.id}`); } catch (e) { message.error((e as Error).message); } }
onMounted(() => { load(); timer = setInterval(() => { if ([...builds.value, ...runs.value].some(b => ['RUNNING', 'QUEUED'].includes(b.state))) load(); }, 2000); }); onBeforeUnmount(() => clearInterval(timer));
async function inspect(id: string) { try { selected.value = await api(`/builds/${id}`); show.value = true; } catch (e) { message.error((e as Error).message); } }
async function inspectRun(id: string) { try { selectedRun.value = await api(`/test-runs/${id}`); showRun.value = true; } catch (e) { message.error((e as Error).message); } }
async function runAction(action: 'cancel' | 'retry') { try { const r = await api(`/test-runs/${selectedRun.value.id}/${action}`, { method: 'POST', ...(action === 'retry' ? { body: JSON.stringify({ requestKey: crypto.randomUUID() }) } : {}) }); if (action === 'retry') selectedRun.value = await api(`/test-runs/${r.id}`); await load(); } catch (e) { message.error((e as Error).message); } }
</script>
<template><div class="page-heading"><div><h1>任务中心</h1><p>查看后台保存的真实状态、执行版本、日志和历史产物</p></div><NButton @click="load">刷新</NButton></div><NTabs v-model:value="tab" type="segment" class="task-kind-tabs"><NTab name="judge">Judge · 出题与验收</NTab><NTab name="tex">TeX · 资料出版</NTab></NTabs><div class="panel"><template v-if="tab === 'judge'"><table v-if="runs.length" class="data-table"><thead><tr><th>任务</th><th>状态与有效性</th><th>真实处理进度</th><th>创建时间</th><th></th></tr></thead><tbody><tr v-for="r in runs" :key="r.id"><td>{{ judgePurposeLabels[r.purpose as JudgePurpose] }}<small>{{ r.id }}</small></td><td><NTag :type="r.state === 'FAILED' ? 'error' : r.state === 'SUCCEEDED' && r.accepted !== false ? 'success' : 'default'">{{ r.state }}</NTag><small>{{ r.stale ? '历史结果已过期' : r.accepted === false ? '未通过验收' : '对应当前依赖版本' }}</small></td><td>{{ r.completed }} / {{ r.total }}<small>{{ r.stage }}</small></td><td>{{ new Date(r.createdAt).toLocaleString('zh-CN') }}</td><td><NButton size="small" @click="inspectRun(r.id)">矩阵与日志</NButton></td></tr></tbody></table><NEmpty v-else description="没有 Judge 任务" class="empty"/></template><template v-else><table v-if="builds.length" class="data-table"><thead><tr><th>任务</th><th>状态</th><th>创建时间</th><th></th></tr></thead><tbody><tr v-for="b in builds" :key="b.id"><td>{{ b.kind }}<small>{{ b.purpose }} · {{ b.id }}</small></td><td><NTag :type="b.state === 'SUCCEEDED' ? 'success' : b.state === 'FAILED' ? 'error' : 'default'">{{ b.state }}</NTag></td><td>{{ new Date(b.createdAt).toLocaleString('zh-CN') }}</td><td><NButton size="small" @click="inspect(b.id)">日志与产物</NButton></td></tr></tbody></table><NEmpty v-else description="没有 TeX 任务" class="empty"/></template></div><NModal v-model:show="show" preset="card" title="TeX 构建记录" style="width: min(1100px, 95vw)"><template v-if="selected"><NAlert v-if="selected.errorCode" type="error">{{ selected.errorCode }}</NAlert><PdfPreview v-if="selected.artifacts.length" :artifact-id="selected.artifacts[0].id"/><pre class="build-log">{{ selected.log || selected.state }}</pre></template></NModal><NModal v-model:show="showRun" preset="card" title="Judge 任务记录" style="width: min(1300px, 96vw)"><JudgeReport v-if="selectedRun" :run="selectedRun" writable @cancel="runAction('cancel')" @retry="runAction('retry')"/></NModal></template>
